//------------------------------------------------------------------------------
// <auto-generated>
//     ?????????
//     ?????:4.0.30319.42000
//
//     ??????????????????,????
//     ??????,?????????
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glowworm.Setup.Locale {
    using System;
    
    
    /// <summary>
    ///   ?????????,?????????????
    /// </summary>
    // ???? StronglyTypedResourceBuilder
    // ?????? ResGen ? Visual Studio ?????????
    // ?????????,??? .ResX ??,?????? ResGen
    // (? /str ??????),????? VS ???
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   ?????????? ResourceManager ???
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glowworm.Setup.Locale.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   ??????? CurrentUICulture ??,?
        ///   ?????????????????????
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ???? All files can be safely deleted. ????????
        /// </summary>
        internal static string AllFilesCanBeSafelyDeleted {
            get {
                return ResourceManager.GetString("AllFilesCanBeSafelyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? An error occurred during installation ????????
        /// </summary>
        internal static string AnErrorOccurredDuringInstallation {
            get {
                return ResourceManager.GetString("AnErrorOccurredDuringInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? An error occurred during the update ????????
        /// </summary>
        internal static string AnErrorOccurredDuringTheUpdate {
            get {
                return ResourceManager.GetString("AnErrorOccurredDuringTheUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? An error occurred during uninstallation ????????
        /// </summary>
        internal static string AnErrorOccurredDuringUninstallation {
            get {
                return ResourceManager.GetString("AnErrorOccurredDuringUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? A setup program is already running. ????????
        /// </summary>
        internal static string ASetupIsAlreadyRunning {
            get {
                return ResourceManager.GetString("ASetupIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Check failed. Unable to guarantee the safety of the uninstallation operation. ????????
        /// </summary>
        internal static string CannotGuaranteeSafetyOfUninstallation {
            get {
                return ResourceManager.GetString("CannotGuaranteeSafetyOfUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Change ????????
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Game Launcher for miHoYo ????????
        /// </summary>
        internal static string GameLauncherForMiHoYo {
            get {
                return ResourceManager.GetString("GameLauncherForMiHoYo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? I acknowledge the above risks ????????
        /// </summary>
        internal static string IAcknowledgeTheAboveRisks {
            get {
                return ResourceManager.GetString("IAcknowledgeTheAboveRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? I have read and agree to the Privacy Policy ????????
        /// </summary>
        internal static string IHaveReadAndAgreeToThePrivacyPolicy {
            get {
                return ResourceManager.GetString("IHaveReadAndAgreeToThePrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Install ????????
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Keep cached data ????????
        /// </summary>
        internal static string KeepCachedData {
            get {
                return ResourceManager.GetString("KeepCachedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Your OS version is below Windows 10 1809 (Build 17763). Please upgrade to the latest version of Windows to continue installing Glowworm. ????????
        /// </summary>
        internal static string OSVersionLessThan17763 {
            get {
                return ResourceManager.GetString("OSVersionLessThan17763", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? The selected folder is on a removable device. It is recommended to download the Portable version. ????????
        /// </summary>
        internal static string RemovableDeviceDownloadPortable {
            get {
                return ResourceManager.GetString("RemovableDeviceDownloadPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Space Available ????????
        /// </summary>
        internal static string SpaceAvailable {
            get {
                return ResourceManager.GetString("SpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Space Required ????????
        /// </summary>
        internal static string SpaceRequired {
            get {
                return ResourceManager.GetString("SpaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Glowworm ({0}) is running. Do you want to force close it? ????????
        /// </summary>
        internal static string GlowwormIsRunningForceClose {
            get {
                return ResourceManager.GetString("GlowwormIsRunningForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Glowworm, Launch! ????????
        /// </summary>
        internal static string GlowwormLaunch {
            get {
                return ResourceManager.GetString("GlowwormLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Glowworm Setup ????????
        /// </summary>
        internal static string GlowwormSetup {
            get {
                return ResourceManager.GetString("GlowwormSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Glowworm Uninstaller ????????
        /// </summary>
        internal static string GlowwormUninstaller {
            get {
                return ResourceManager.GetString("GlowwormUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Glowworm Updater ????????
        /// </summary>
        internal static string GlowwormUpdater {
            get {
                return ResourceManager.GetString("GlowwormUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? The destination folder does not exist. Please try again. ????????
        /// </summary>
        internal static string TheDestinationFolderDoesNotExistPleaseTryAgain {
            get {
                return ResourceManager.GetString("TheDestinationFolderDoesNotExistPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Uninstall ????????
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Uninstallation Complete ????????
        /// </summary>
        internal static string UninstallationComplete {
            get {
                return ResourceManager.GetString("UninstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? The installation path is incorrect or the folder has been moved. To avoid accidentally deleting files, the uninstall function is disabled. Please delete the files manually. ????????
        /// </summary>
        internal static string UninstallPathCaution {
            get {
                return ResourceManager.GetString("UninstallPathCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? The database file GlowwormDatabase.db exists in the installation directory. Personal data will be lost after uninstallation. ????????
        /// </summary>
        internal static string UnstallDatabaseCaution {
            get {
                return ResourceManager.GetString("UnstallDatabaseCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Game screenshot files exist in the installation directory. These files will be deleted after uninstallation. ????????
        /// </summary>
        internal static string UnstallScreenshotCaution {
            get {
                return ResourceManager.GetString("UnstallScreenshotCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Update ????????
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}



