//------------------------------------------------------------------------------
// <auto-generated>
//     ?????????
//     ?????:4.0.30319.42000
//
//     ??????????????????,????
//     ??????,?????????
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glowworm.Language {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glowworm.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ???? Network Error ????????
        /// </summary>
        public static string SettingPage_TestCDNAsync_NetworkError {
            get {
                return ResourceManager.GetString("SettingPage_TestCDNAsync_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Test Network ????????
        /// </summary>
        public static string SettingPage_TestNetwork {
            get {
                return ResourceManager.GetString("SettingPage_TestNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Test URL Protocol ????????
        /// </summary>
        public static string SettingPage_TestURLProtocol {
            get {
                return ResourceManager.GetString("SettingPage_TestURLProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? The current location of the data folder is: ????????
        /// </summary>
        public static string SettingPage_TheCurrentLocationOfTheDataFolderIs {
            get {
                return ResourceManager.GetString("SettingPage_TheCurrentLocationOfTheDataFolderIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Automatically calculate the theme color based on the background image, and use the system theme color by default. ????????
        /// </summary>
        public static string SettingPage_ThemeColorDesc {
            get {
                return ResourceManager.GetString("SettingPage_ThemeColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? This is a Logo ????????
        /// </summary>
        public static string SettingPage_ThisIsALogo {
            get {
                return ResourceManager.GetString("SettingPage_ThisIsALogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Toolbox ????????
        /// </summary>
        public static string SettingPage_Toolbox {
            get {
                return ResourceManager.GetString("SettingPage_Toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Update ????????
        /// </summary>
        public static string SettingPage_Update {
            get {
                return ResourceManager.GetString("SettingPage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Other software can use some of Glowworm&apos;s features through the URL protocol. ????????
        /// </summary>
        public static string SettingPage_URLProtocolDesc {
            get {
                return ResourceManager.GetString("SettingPage_URLProtocolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? URL Protocol (Experimental) ????????
        /// </summary>
        public static string SettingPage_URLProtocolExperimental {
            get {
                return ResourceManager.GetString("SettingPage_URLProtocolExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Windows Size ????????
        /// </summary>
        public static string SettingPage_WindowsSize {
            get {
                return ResourceManager.GetString("SettingPage_WindowsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Would like to reselect? (You need to migrate the data files manually before selecting) ????????
        /// </summary>
        public static string SettingPage_WouldLikeToReselectDataFolder {
            get {
                return ResourceManager.GetString("SettingPage_WouldLikeToReselectDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Import {0} warp record(s) successfully. ????????
        /// </summary>
        public static string StarRailGachaService_ImportWarpRecordsSuccessfully {
            get {
                return ResourceManager.GetString("StarRailGachaService_ImportWarpRecordsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? The screenshot feature does not support cloud game. ????????
        /// </summary>
        public static string TheScreenshotFeatureDoesNotSupportCloudGame {
            get {
                return ResourceManager.GetString("TheScreenshotFeatureDoesNotSupportCloudGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? &quot;{0}&quot; field is missing in a gacha record. ????????
        /// </summary>
        public static string UIGFGachaService_0FieldIsMissingInAGachaRecord {
            get {
                return ResourceManager.GetString("UIGFGachaService_0FieldIsMissingInAGachaRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Import successful. ????????
        /// </summary>
        public static string UIGFGachaService_ImportSuccessful {
            get {
                return ResourceManager.GetString("UIGFGachaService_ImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Import successful, but some records are missing item names. Please go to the gacha record settings, change the language, and apply. ????????
        /// </summary>
        public static string UIGFGachaService_ImportSuccessfulButNoRecordItemName {
            get {
                return ResourceManager.GetString("UIGFGachaService_ImportSuccessfulButNoRecordItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Uid mismatch detected. Expected: {0}, but found: {1}. ????????
        /// </summary>
        public static string UIGFGachaService_UidMismatchDetectedExpected0ButFound1 {
            get {
                return ResourceManager.GetString("UIGFGachaService_UidMismatchDetectedExpected0ButFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Clean Registry ????????
        /// </summary>
        public static string UninstallGameDialog_CleanRegistry {
            get {
                return ResourceManager.GetString("UninstallGameDialog_CleanRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Delete Game Assets ????????
        /// </summary>
        public static string UninstallGameDialog_DeleteGameAssets {
            get {
                return ResourceManager.GetString("UninstallGameDialog_DeleteGameAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Delete Temporary Files ????????
        /// </summary>
        public static string UninstallGameDialog_DeleteTemporaryFiles {
            get {
                return ResourceManager.GetString("UninstallGameDialog_DeleteTemporaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? The official launcher needs to be uninstalled by yourself. ????????
        /// </summary>
        public static string UninstallGameDialog_OfficalLauncherTip {
            get {
                return ResourceManager.GetString("UninstallGameDialog_OfficalLauncherTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Choose the steps of uninstallation. The uninstallation takes a long time, so please be patient. ????????
        /// </summary>
        public static string UninstallGameDialog_StepTip {
            get {
                return ResourceManager.GetString("UninstallGameDialog_StepTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Click to Refresh ????????
        /// </summary>
        public static string UpdateContentWindow_ClickToRefresh {
            get {
                return ResourceManager.GetString("UpdateContentWindow_ClickToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Recently Updated Content ????????
        /// </summary>
        public static string UpdateContentWindow_RecentlyUpdatedContent {
            get {
                return ResourceManager.GetString("UpdateContentWindow_RecentlyUpdatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Architecture: ????????
        /// </summary>
        public static string UpdatePage_Architecture {
            get {
                return ResourceManager.GetString("UpdatePage_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Build Time: ????????
        /// </summary>
        public static string UpdatePage_BuiltTime {
            get {
                return ResourceManager.GetString("UpdatePage_BuiltTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Dev Channel ????????
        /// </summary>
        public static string UpdatePage_DevChannel {
            get {
                return ResourceManager.GetString("UpdatePage_DevChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Download Installer ????????
        /// </summary>
        public static string UpdatePage_DownloadInstaller {
            get {
                return ResourceManager.GetString("UpdatePage_DownloadInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Download Portable ????????
        /// </summary>
        public static string UpdatePage_DownloadPortable {
            get {
                return ResourceManager.GetString("UpdatePage_DownloadPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Ignore this Version ????????
        /// </summary>
        public static string UpdatePage_IgnoreThisVersion {
            get {
                return ResourceManager.GetString("UpdatePage_IgnoreThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Links: ????????
        /// </summary>
        public static string UpdatePage_Links {
            get {
                return ResourceManager.GetString("UpdatePage_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? New Version! ????????
        /// </summary>
        public static string UpdatePage_NewVersion {
            get {
                return ResourceManager.GetString("UpdatePage_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Preview Channel ????????
        /// </summary>
        public static string UpdatePage_PreviewChannel {
            get {
                return ResourceManager.GetString("UpdatePage_PreviewChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Release Channel: ????????
        /// </summary>
        public static string UpdatePage_ReleaseChannel {
            get {
                return ResourceManager.GetString("UpdatePage_ReleaseChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Release Page ????????
        /// </summary>
        public static string UpdatePage_ReleasePage {
            get {
                return ResourceManager.GetString("UpdatePage_ReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Remind me Later ????????
        /// </summary>
        public static string UpdatePage_RemindLatter {
            get {
                return ResourceManager.GetString("UpdatePage_RemindLatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Stable Channel ????????
        /// </summary>
        public static string UpdatePage_StableChannel {
            get {
                return ResourceManager.GetString("UpdatePage_StableChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Update Now ????????
        /// </summary>
        public static string UpdatePage_UpdateNow {
            get {
                return ResourceManager.GetString("UpdatePage_UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? You need to manually download the new version package ????????
        /// </summary>
        public static string UpdatePage_YouNeedToManuallyDownloadTheNewVersionPackage {
            get {
                return ResourceManager.GetString("UpdatePage_YouNeedToManuallyDownloadTheNewVersionPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Cannot update automatically ????????
        /// </summary>
        public static string UpdateService_CannotUpdateAutomatically {
            get {
                return ResourceManager.GetString("UpdateService_CannotUpdateAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Auto-restart after update ????????
        /// </summary>
        public static string UpdateWindow_AutoRestartAfterUpdate {
            get {
                return ResourceManager.GetString("UpdateWindow_AutoRestartAfterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Display update content after restart ????????
        /// </summary>
        public static string UpdateWindow_DisplayUpdateContentAfterRestart {
            get {
                return ResourceManager.GetString("UpdateWindow_DisplayUpdateContentAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Full Package ????????
        /// </summary>
        public static string UpdateWindow_FullPackage {
            get {
                return ResourceManager.GetString("UpdateWindow_FullPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Migrate to Setup ????????
        /// </summary>
        public static string UpdateWindow_MigrateToSetup {
            get {
                return ResourceManager.GetString("UpdateWindow_MigrateToSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Before starting, some necessary environment checks are required. ????????
        /// </summary>
        public static string WelcomeView_BeforeStartingSomeNecessaryEnvironmentChecksAreRequired {
            get {
                return ResourceManager.GetString("WelcomeView_BeforeStartingSomeNecessaryEnvironmentChecksAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Dear Player, welcome to Glowworm! ????????
        /// </summary>
        public static string WelcomeView_DearPlayerWelcomeToGlowworm {
            get {
                return ResourceManager.GetString("WelcomeView_DearPlayerWelcomeToGlowworm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? If Glowworm takes a long time to start, it is recommended to disable Smart App Control in Windows Security. ????????
        /// </summary>
        public static string WelcomeView_IfGlowwormTakesALongTimeToStartItIsRecommendedToDisableSmartAppControlInWindowsSecurity {
            get {
                return ResourceManager.GetString("WelcomeView_IfGlowwormTakesALongTimeToStartItIsRecommendedToDisableSmartAppContro" +
                        "lInWindowsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Installed ????????
        /// </summary>
        public static string WelcomeView_Installed {
            get {
                return ResourceManager.GetString("WelcomeView_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Install Now ????????
        /// </summary>
        public static string WelcomeView_InstallNow {
            get {
                return ResourceManager.GetString("WelcomeView_InstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Learn More ????????
        /// </summary>
        public static string WelcomeView_LearnMore {
            get {
                return ResourceManager.GetString("WelcomeView_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Network error. You can continue using Glowworm, but you won&apos;t receive future updates. ????????
        /// </summary>
        public static string WelcomeView_NetworkErrorYouCanContinueUsingGlowwormButYouWonTReceiveFutureUpdates {
            get {
                return ResourceManager.GetString("WelcomeView_NetworkErrorYouCanContinueUsingGlowwormButYouWonTReceiveFutureUpdates" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Network Status ????????
        /// </summary>
        public static string WelcomeView_NetworkStatus {
            get {
                return ResourceManager.GetString("WelcomeView_NetworkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Not Installed ????????
        /// </summary>
        public static string WelcomeView_NotInstalled {
            get {
                return ResourceManager.GetString("WelcomeView_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Open Windows Security ????????
        /// </summary>
        public static string WelcomeView_OpenWindowsSecurity {
            get {
                return ResourceManager.GetString("WelcomeView_OpenWindowsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? All your personal data will be stored in the folder below. It is important, and you can also click the button below to select a different folder. ????????
        /// </summary>
        public static string WelcomeView_SelectUserDataFolderDescription {
            get {
                return ResourceManager.GetString("WelcomeView_SelectUserDataFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Glowworm, Start! ????????
        /// </summary>
        public static string WelcomeView_GlowwormStart {
            get {
                return ResourceManager.GetString("WelcomeView_GlowwormStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? This is a launcher designed specifically for HoYoverse games, helping you easily manage your games and enjoy a better experience. ????????
        /// </summary>
        public static string WelcomeView_WelcomeToGlowwormDescription {
            get {
                return ResourceManager.GetString("WelcomeView_WelcomeToGlowwormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Export to Folder ????????
        /// </summary>
        public static string ZZZGachaInfoWindow_ExportToFolder {
            get {
                return ResourceManager.GetString("ZZZGachaInfoWindow_ExportToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Fetch Data for All Languages ????????
        /// </summary>
        public static string ZZZGachaInfoWindow_FetchDataForAllLanguages {
            get {
                return ResourceManager.GetString("ZZZGachaInfoWindow_FetchDataForAllLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Miyoushe ????????
        /// </summary>
        public static string ZZZGachaInfoWindow_Miyoushe {
            get {
                return ResourceManager.GetString("ZZZGachaInfoWindow_Miyoushe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Save to Database ????????
        /// </summary>
        public static string ZZZGachaInfoWindow_SaveToDatabase {
            get {
                return ResourceManager.GetString("ZZZGachaInfoWindow_SaveToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? This tool is used to update item images in Zenless Zone Zero gacha records.
        ///Click &quot;Miyoushe&quot; or &quot;HoYoLAB&quot; in the top left corner, log in, and wait for the data to be retrieved. If logging in via HoYoLAB, you also need to click &quot;Fetch Data for All Languages&quot;.
        ///After retrieving the data, you can save it to the database in any language or export it to a folder.
        ///You are welcome to submit the exported data to the following repository: ????????
        /// </summary>
        public static string ZZZGachaInfoWindow_ZZZGachaInfoWindowGuide {
            get {
                return ResourceManager.GetString("ZZZGachaInfoWindow_ZZZGachaInfoWindowGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Import {0} signal search record(s) successfully. ????????
        /// </summary>
        public static string ZZZGachaService_ImportSignalSearchRecordsSuccessfully {
            get {
                return ResourceManager.GetString("ZZZGachaService_ImportSignalSearchRecordsSuccessfully", resourceCulture);
            }
        }
        public static string GachaStatsCard_Pity { get { return ResourceManager.GetString("GachaStatsCard_Pity", resourceCulture); } }
        public static string GachaStatsCard_Average { get { return ResourceManager.GetString("GachaStatsCard_Average", resourceCulture); } }
        public static string GachaStatsCard_Stats { get { return ResourceManager.GetString("GachaStatsCard_Stats", resourceCulture); } }
        public static string DownloadGamePage_CloseSoftware { get { return ResourceManager.GetString("DownloadGamePage_CloseSoftware", resourceCulture); } }
        public static string DownloadGamePage_CloseSoftwareContent { get { return ResourceManager.GetString("DownloadGamePage_CloseSoftwareContent", resourceCulture); } }
        public static string DownloadGamePage_Close { get { return ResourceManager.GetString("DownloadGamePage_Close", resourceCulture); } }
        public static string Common_Cancel { get { return ResourceManager.GetString("Common_Cancel", resourceCulture); } }
        public static string DownloadGamePage_SoftwareWillBeExitedSoon { get { return ResourceManager.GetString("DownloadGamePage_SoftwareWillBeExitedSoon", resourceCulture); } }
        public static string DownloadGamePage_RepeatStart { get { return ResourceManager.GetString("DownloadGamePage_RepeatStart", resourceCulture); } }
        public static string Common_Confirm { get { return ResourceManager.GetString("Common_Confirm", resourceCulture); } }
        public static string DownloadGamePage_ParameterError { get { return ResourceManager.GetString("DownloadGamePage_ParameterError", resourceCulture); } }
        public static string DownloadGamePage_NoPermission { get { return ResourceManager.GetString("DownloadGamePage_NoPermission", resourceCulture); } }
        public static string DownloadGamePage_PleaseStartAsAdministrator { get { return ResourceManager.GetString("DownloadGamePage_PleaseStartAsAdministrator", resourceCulture); } }
        public static string DownloadGamePage_Start { get { return ResourceManager.GetString("DownloadGamePage_Start", resourceCulture); } }
        public static string DownloadGamePage_Preparing { get { return ResourceManager.GetString("DownloadGamePage_Preparing", resourceCulture); } }
        public static string DownloadGamePage_Downloading { get { return ResourceManager.GetString("DownloadGamePage_Downloading", resourceCulture); } }
        public static string DownloadGamePage_Verifying { get { return ResourceManager.GetString("DownloadGamePage_Verifying", resourceCulture); } }
        public static string DownloadGamePage_Decompressing { get { return ResourceManager.GetString("DownloadGamePage_Decompressing", resourceCulture); } }
        public static string DownloadGamePage_SomethingError { get { return ResourceManager.GetString("DownloadGamePage_SomethingError", resourceCulture); } }
        public static string DownloadGamePage_Retry { get { return ResourceManager.GetString("DownloadGamePage_Retry", resourceCulture); } }
        public static string DownloadGamePage_OpenLog { get { return ResourceManager.GetString("DownloadGamePage_OpenLog", resourceCulture); } }
        public static string DownloadGamePage_NetworkError { get { return ResourceManager.GetString("DownloadGamePage_NetworkError", resourceCulture); } }
        public static string DownloadGamePage_UnknownError { get { return ResourceManager.GetString("DownloadGamePage_UnknownError", resourceCulture); } }
        public static string DownloadGamePage_Finished { get { return ResourceManager.GetString("DownloadGamePage_Finished", resourceCulture); } }
        public static string DownloadGamePage_Pause { get { return ResourceManager.GetString("DownloadGamePage_Pause", resourceCulture); } }
        public static string DownloadGamePage_Skip { get { return ResourceManager.GetString("DownloadGamePage_Skip", resourceCulture); } }
        public static string DownloadGamePage_VerifyFailed { get { return ResourceManager.GetString("DownloadGamePage_VerifyFailed", resourceCulture); } }
        public static string DownloadGamePage_TheFollowingFileVerifyFailed { get { return ResourceManager.GetString("DownloadGamePage_TheFollowingFileVerifyFailed", resourceCulture); } }
        public static string DownloadGamePage_Redownload { get { return ResourceManager.GetString("DownloadGamePage_Redownload", resourceCulture); } }
        public static string DownloadGamePage_Ignore { get { return ResourceManager.GetString("DownloadGamePage_Ignore", resourceCulture); } }
        public static string DownloadGamePage_Stop { get { return ResourceManager.GetString("DownloadGamePage_Stop", resourceCulture); } }
        public static string DownloadGamePage_SkipVerificationContent { get { return ResourceManager.GetString("DownloadGamePage_SkipVerificationContent", resourceCulture); } }
        public static string DownloadGamePage_SkipVerification { get { return ResourceManager.GetString("DownloadGamePage_SkipVerification", resourceCulture); } }
        public static string DownloadGamePage_DownloadPaused { get { return ResourceManager.GetString("DownloadGamePage_DownloadPaused", resourceCulture); } }
        public static string GachaLogPage_NoGachaRecords { get { return ResourceManager.GetString("GachaLogPage_NoGachaRecords", resourceCulture); } }
        public static string GachaLogPage_UpdateRecords { get { return ResourceManager.GetString("GachaLogPage_UpdateRecords", resourceCulture); } }
        public static string GachaLogPage_UpdateSavedURL { get { return ResourceManager.GetString("GachaLogPage_UpdateSavedURL", resourceCulture); } }
        public static string GachaLogPage_UpdateAll { get { return ResourceManager.GetString("GachaLogPage_UpdateAll", resourceCulture); } }
        public static string GachaLogPage_InputURL { get { return ResourceManager.GetString("GachaLogPage_InputURL", resourceCulture); } }
        public static string Common_Setting { get { return ResourceManager.GetString("Common_Setting", resourceCulture); } }
        public static string GachaLogPage_OtherSettings { get { return ResourceManager.GetString("GachaLogPage_OtherSettings", resourceCulture); } }
        public static string GachaLogPage_CopyURL { get { return ResourceManager.GetString("GachaLogPage_CopyURL", resourceCulture); } }
        public static string GachaLogPage_AuthkeyTimeoutAlwaysOccurs { get { return ResourceManager.GetString("GachaLogPage_AuthkeyTimeoutAlwaysOccurs", resourceCulture); } }
        public static string GachaLogPage_ClearURLCacheFiles { get { return ResourceManager.GetString("GachaLogPage_ClearURLCacheFiles", resourceCulture); } }
        public static string GachaLogPage_ExportAs { get { return ResourceManager.GetString("GachaLogPage_ExportAs", resourceCulture); } }
        public static string GachaLogPage_ImportFromJson { get { return ResourceManager.GetString("GachaLogPage_ImportFromJson", resourceCulture); } }
        public static string GachaLogPage_ShowNoviceGachaType { get { return ResourceManager.GetString("GachaLogPage_ShowNoviceGachaType", resourceCulture); } }
        public static string GachaLogPage_DeleteRecords { get { return ResourceManager.GetString("GachaLogPage_DeleteRecords", resourceCulture); } }
        public static string GachaLogPage_Language { get { return ResourceManager.GetString("GachaLogPage_Language", resourceCulture); } }
        public static string GachaLogPage_CannotFindSavedURLOfUid { get { return ResourceManager.GetString("GachaLogPage_CannotFindSavedURLOfUid", resourceCulture); } }
        public static string GachaLogPage_GameNotInstalled { get { return ResourceManager.GetString("GachaLogPage_GameNotInstalled", resourceCulture); } }
        public static string GachaLogPage_CannotFindURL { get { return ResourceManager.GetString("GachaLogPage_CannotFindURL", resourceCulture); } }
        public static string GachaLogPage_OperationCanceled { get { return ResourceManager.GetString("GachaLogPage_OperationCanceled", resourceCulture); } }
        public static string GachaLogPage_OnlySupportZZZCNServer { get { return ResourceManager.GetString("GachaLogPage_OnlySupportZZZCNServer", resourceCulture); } }
        public static string GachaLogPage_PleaseLoginMiyousheAndAddZZZRole { get { return ResourceManager.GetString("GachaLogPage_PleaseLoginMiyousheAndAddZZZRole", resourceCulture); } }
        public static string GachaLogPage_CurrentAccountMissingCookiePleaseReloginMiyoushe { get { return ResourceManager.GetString("GachaLogPage_CurrentAccountMissingCookiePleaseReloginMiyoushe", resourceCulture); } }
        public static string GachaLogPage_SelectMiyousheRole { get { return ResourceManager.GetString("GachaLogPage_SelectMiyousheRole", resourceCulture); } }
        public static string GachaLogPage_SelectMiyousheRoleDescription { get { return ResourceManager.GetString("GachaLogPage_SelectMiyousheRoleDescription", resourceCulture); } }
        public static string GachaLogPage_PleaseSelectMiyousheRole { get { return ResourceManager.GetString("GachaLogPage_PleaseSelectMiyousheRole", resourceCulture); } }
        public static string GachaLogPage_PleaseOpenTheGachaRecordsPageInGameAndTryAgain { get { return ResourceManager.GetString("GachaLogPage_PleaseOpenTheGachaRecordsPageInGameAndTryAgain", resourceCulture); } }
        public static string Common_Warning { get { return ResourceManager.GetString("Common_Warning", resourceCulture); } }
        public static string Common_Delete { get { return ResourceManager.GetString("Common_Delete", resourceCulture); } }
        public static string GachaLogPage_DeletedGachaRecordsOfUid { get { return ResourceManager.GetString("GachaLogPage_DeletedGachaRecordsOfUid", resourceCulture); } }
        public static string GachaLogPage_DeleteGachaRecordsWarning { get { return ResourceManager.GetString("GachaLogPage_DeleteGachaRecordsWarning", resourceCulture); } }
        public static string GachaLogService_WishRecords { get { return ResourceManager.GetString("GachaLogService_WishRecords", resourceCulture); } }
        public static string GachaLogService_WarpRecords { get { return ResourceManager.GetString("GachaLogService_WarpRecords", resourceCulture); } }
        public static string GachaLogService_GettingUid { get { return ResourceManager.GetString("GachaLogService_GettingUid", resourceCulture); } }
        public static string GachaLogService_ThisAccountHasNoGachaRecordsInTheLast6Months { get { return ResourceManager.GetString("GachaLogService_ThisAccountHasNoGachaRecordsInTheLast6Months", resourceCulture); } }
        public static string GachaLogService_GetGachaResult { get { return ResourceManager.GetString("GachaLogService_GetGachaResult", resourceCulture); } }
        public static string GenshinGachaService_ImportWishRecordsSuccessfully { get { return ResourceManager.GetString("GenshinGachaService_ImportWishRecordsSuccessfully", resourceCulture); } }
        public static string Common_Apply { get { return ResourceManager.GetString("Common_Apply", resourceCulture); } }
        public static string Common_Refresh { get { return ResourceManager.GetString("Common_Refresh", resourceCulture); } }
        public static string Common_Save { get { return ResourceManager.GetString("Common_Save", resourceCulture); } }
        public static string Common_Select { get { return ResourceManager.GetString("Common_Select", resourceCulture); } }
        public static string Common_Start { get { return ResourceManager.GetString("Common_Start", resourceCulture); } }
        public static string Common_Continue { get { return ResourceManager.GetString("Common_Continue", resourceCulture); } }
        public static string MainPage_HowToSwitchGameRegion { get { return ResourceManager.GetString("MainPage_HowToSwitchGameRegion", resourceCulture); } }
        public static string MainPage_ClickTheRightMouseButtonOnTheGameIconOnTheLeft { get { return ResourceManager.GetString("MainPage_ClickTheRightMouseButtonOnTheGameIconOnTheLeft", resourceCulture); } }
        public static string MainPage_Launcer { get { return ResourceManager.GetString("MainPage_Launcer", resourceCulture); } }
        public static string MainPage_GameScreenshot { get { return ResourceManager.GetString("MainPage_GameScreenshot", resourceCulture); } }
        public static string ScreenshotPage_GameScreenshot { get { return ResourceManager.GetString("ScreenshotPage_GameScreenshot", resourceCulture); } }
        public static string ScreenshotPage_OpenFolder { get { return ResourceManager.GetString("ScreenshotPage_OpenFolder", resourceCulture); } }
        public static string SettingPage_Log { get { return ResourceManager.GetString("SettingPage_Log", resourceCulture); } }
        public static string SettingPage_ShowConsole { get { return ResourceManager.GetString("SettingPage_ShowConsole", resourceCulture); } }
        public static string SettingPage_AppSettings { get { return ResourceManager.GetString("SettingPage_AppSettings", resourceCulture); } }
        public static string SettingPage_EffectiveAtNextStartup { get { return ResourceManager.GetString("SettingPage_EffectiveAtNextStartup", resourceCulture); } }
        public static string SettingPage_OpenLogFolder { get { return ResourceManager.GetString("SettingPage_OpenLogFolder", resourceCulture); } }
        public static string SettingPage_Normal { get { return ResourceManager.GetString("SettingPage_Normal", resourceCulture); } }
        public static string SettingPage_Small { get { return ResourceManager.GetString("SettingPage_Small", resourceCulture); } }
        public static string SettingPage_AppBackground { get { return ResourceManager.GetString("SettingPage_AppBackground", resourceCulture); } }
        public static string SettingPage_CustomBackgroundSupportVideo { get { return ResourceManager.GetString("SettingPage_CustomBackgroundSupportVideo", resourceCulture); } }
        public static string SettingPage_DynamicThemeColor { get { return ResourceManager.GetString("SettingPage_DynamicThemeColor", resourceCulture); } }
        public static string SettingPage_CloudFlareConnectProperly { get { return ResourceManager.GetString("SettingPage_CloudFlareConnectProperly", resourceCulture); } }
        public static string SettingPage_CheckForUpdate { get { return ResourceManager.GetString("SettingPage_CheckForUpdate", resourceCulture); } }
        public static string SettingPage_CurrentVersion { get { return ResourceManager.GetString("SettingPage_CurrentVersion", resourceCulture); } }
        public static string SettingPage_JoinPreviewReleaseChannel { get { return ResourceManager.GetString("SettingPage_JoinPreviewReleaseChannel", resourceCulture); } }
        public static string SettingPage_FileManager { get { return ResourceManager.GetString("SettingPage_FileManager", resourceCulture); } }
        public static string SettingPage_OpenDataFolder { get { return ResourceManager.GetString("SettingPage_OpenDataFolder", resourceCulture); } }
        public static string SettingPage_ReselectDataFolder { get { return ResourceManager.GetString("SettingPage_ReselectDataFolder", resourceCulture); } }
        public static string SettingPage_DeleteAllSettings { get { return ResourceManager.GetString("SettingPage_DeleteAllSettings", resourceCulture); } }
        public static string SettingPage_ClearCachedFiles { get { return ResourceManager.GetString("SettingPage_ClearCachedFiles", resourceCulture); } }
        public static string SettingPage_About { get { return ResourceManager.GetString("SettingPage_About", resourceCulture); } }
        public static string SettingPage_ProjectHomepage { get { return ResourceManager.GetString("SettingPage_ProjectHomepage", resourceCulture); } }
        public static string SettingPage_ReportIssue { get { return ResourceManager.GetString("SettingPage_ReportIssue", resourceCulture); } }
        public static string SettingPage_ReleaseHistory { get { return ResourceManager.GetString("SettingPage_ReleaseHistory", resourceCulture); } }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Project.
        /// </summary>
        public static string SettingPage_OriginalProject { get { return ResourceManager.GetString("SettingPage_OriginalProject", resourceCulture); } }
        public static string Common_Yes { get { return ResourceManager.GetString("Common_Yes", resourceCulture); } }
        public static string SettingPage_AfterDeletingTheSoftwareWillBeRestartedAutomatically { get { return ResourceManager.GetString("SettingPage_AfterDeletingTheSoftwareWillBeRestartedAutomatically", resourceCulture); } }
        public static string GachaLogPage_GachaLanguageDesc { get { return ResourceManager.GetString("GachaLogPage_GachaLanguageDesc", resourceCulture); } }
        public static string SettingPage_Language { get { return ResourceManager.GetString("SettingPage_Language", resourceCulture); } }
        public static string SettingPage_FollowSystem { get { return ResourceManager.GetString("SettingPage_FollowSystem", resourceCulture); } }
        public static string GachaLogService_GetGachaProgressText { get { return ResourceManager.GetString("GachaLogService_GetGachaProgressText", resourceCulture); } }
        public static string Common_Summary { get { return ResourceManager.GetString("Common_Summary", resourceCulture); } }
        public static string Common_Accept { get { return ResourceManager.GetString("Common_Accept", resourceCulture); } }
        public static string Common_Reject { get { return ResourceManager.GetString("Common_Reject", resourceCulture); } }
        public static string Common_Disclaimer { get { return ResourceManager.GetString("Common_Disclaimer", resourceCulture); } }
        public static string Common_AccountError { get { return ResourceManager.GetString("Common_AccountError", resourceCulture); } }
        public static string Common_NetworkError { get { return ResourceManager.GetString("Common_NetworkError", resourceCulture); } }
        public static string ScreenshotPage_ScreenshotFolderDoesNotExist { get { return ResourceManager.GetString("ScreenshotPage_ScreenshotFolderDoesNotExist", resourceCulture); } }
        public static string GachaLogPage_0GachaItemsHaveBeenChangedToLanguage1 { get { return ResourceManager.GetString("GachaLogPage_0GachaItemsHaveBeenChangedToLanguage1", resourceCulture); } }
        public static string SettingPage_PrivacyPolicy { get { return ResourceManager.GetString("SettingPage_PrivacyPolicy", resourceCulture); } }
        public static string MainPage_Tips { get { return ResourceManager.GetString("MainPage_Tips", resourceCulture); } }
        public static string SettingPage_CDNTips { get { return ResourceManager.GetString("SettingPage_CDNTips", resourceCulture); } }
        public static string SettingPage_ExitLauncherWhenClosingWindow { get { return ResourceManager.GetString("SettingPage_ExitLauncherWhenClosingWindow", resourceCulture); } }
        public static string Common_Exit { get { return ResourceManager.GetString("Common_Exit", resourceCulture); } }
        public static string Common_Hide { get { return ResourceManager.GetString("Common_Hide", resourceCulture); } }
        public static string ScreenshotPage_BackupScreenshots { get { return ResourceManager.GetString("ScreenshotPage_BackupScreenshots", resourceCulture); } }
        public static string ScreenshotPage_OpenBackupFolder { get { return ResourceManager.GetString("ScreenshotPage_OpenBackupFolder", resourceCulture); } }
        public static string SettingPage_LastBackup { get { return ResourceManager.GetString("SettingPage_LastBackup", resourceCulture); } }
        public static string SettingPage_BackupDatabase { get { return ResourceManager.GetString("SettingPage_BackupDatabase", resourceCulture); } }
        public static string ScreenshotPage_BackedUpNewScreenshots { get { return ResourceManager.GetString("ScreenshotPage_BackedUpNewScreenshots", resourceCulture); } }
        public static string DownloadGamePage_Merging { get { return ResourceManager.GetString("DownloadGamePage_Merging", resourceCulture); } }
        public static string Common_Attention { get { return ResourceManager.GetString("Common_Attention", resourceCulture); } }
        public static string SettingPage_Donate { get { return ResourceManager.GetString("SettingPage_Donate", resourceCulture); } }
        public static string SettingPage_RegisterURLProtocol { get { return ResourceManager.GetString("SettingPage_RegisterURLProtocol", resourceCulture); } }
        public static string ImageViewPage_ZoomOut { get { return ResourceManager.GetString("ImageViewPage_ZoomOut", resourceCulture); } }
        public static string ImageViewPage_ZoomIn { get { return ResourceManager.GetString("ImageViewPage_ZoomIn", resourceCulture); } }
        public static string ImageViewPage_Rotate { get { return ResourceManager.GetString("ImageViewPage_Rotate", resourceCulture); } }
        public static string Common_Copy { get { return ResourceManager.GetString("Common_Copy", resourceCulture); } }
        public static string Common_Open { get { return ResourceManager.GetString("Common_Open", resourceCulture); } }
        public static string FileSettingPage_DataFolder { get { return ResourceManager.GetString("FileSettingPage_DataFolder", resourceCulture); } }
        public static string FileSettingPage_OpenLogFile { get { return ResourceManager.GetString("FileSettingPage_OpenLogFile", resourceCulture); } }
        public static string SettingPage_Appearance { get { return ResourceManager.GetString("SettingPage_Appearance", resourceCulture); } }
        public static string SettingPage_FileManagement { get { return ResourceManager.GetString("SettingPage_FileManagement", resourceCulture); } }
        public static string SettingPage_Completed { get { return ResourceManager.GetString("SettingPage_Completed", resourceCulture); } }
        public static string AboutSettingPage_Links { get { return ResourceManager.GetString("AboutSettingPage_Links", resourceCulture); } }
        public static string SettingPage_Advanced { get { return ResourceManager.GetString("SettingPage_Advanced", resourceCulture); } }
        public static string SettingPage_Experience { get { return ResourceManager.GetString("SettingPage_Experience", resourceCulture); } }
        public static string FileSettingPage_DataFolderIsImportant { get { return ResourceManager.GetString("FileSettingPage_DataFolderIsImportant", resourceCulture); } }
        public static string AppearanceSettingPage_ThemeColor { get { return ResourceManager.GetString("AppearanceSettingPage_ThemeColor", resourceCulture); } }
        public static string AppearanceSettingPage_ThemeColorDescription { get { return ResourceManager.GetString("AppearanceSettingPage_ThemeColorDescription", resourceCulture); } }
        public static string AppearanceSettingPage_UseSystemThemeColor { get { return ResourceManager.GetString("AppearanceSettingPage_UseSystemThemeColor", resourceCulture); } }
        public static string AppearanceSettingPage_AlwaysDisplayNavigationSidebarIcons { get { return ResourceManager.GetString("AppearanceSettingPage_AlwaysDisplayNavigationSidebarIcons", resourceCulture); } }
        public static string ExperienceSettingPage_Features { get { return ResourceManager.GetString("ExperienceSettingPage_Features", resourceCulture); } }
        public static string ExperienceSettingPage_HideGameAccountSwitcher { get { return ResourceManager.GetString("ExperienceSettingPage_HideGameAccountSwitcher", resourceCulture); } }
        public static string SelectLanguagePage_NetworkTest { get { return ResourceManager.GetString("SelectLanguagePage_NetworkTest", resourceCulture); } }
        public static string SelectLanguagePage_AreYouAbleToReceiveUpdatesForGlowworm { get { return ResourceManager.GetString("SelectLanguagePage_AreYouAbleToReceiveUpdatesForGlowworm", resourceCulture); } }
        public static string ExperienceSettingPage_MinimizeToTaskbar { get { return ResourceManager.GetString("ExperienceSettingPage_MinimizeToTaskbar", resourceCulture); } }
        public static string ExperienceSettingPage_DoNothing { get { return ResourceManager.GetString("ExperienceSettingPage_DoNothing", resourceCulture); } }
        public static string ExperienceSettingPage_AfterStartingGame { get { return ResourceManager.GetString("ExperienceSettingPage_AfterStartingGame", resourceCulture); } }
        public static string AppearanceSettingPage_HelpUsTranslateGlowworm { get { return ResourceManager.GetString("AppearanceSettingPage_HelpUsTranslateGlowworm", resourceCulture); } }
        public static string FileSettingPage_Cache { get { return ResourceManager.GetString("FileSettingPage_Cache", resourceCulture); } }
        public static string FileSettingPage_Log { get { return ResourceManager.GetString("FileSettingPage_Log", resourceCulture); } }
        public static string FileSettingPage_Image { get { return ResourceManager.GetString("FileSettingPage_Image", resourceCulture); } }
        public static string FileSettingPage_Browser { get { return ResourceManager.GetString("FileSettingPage_Browser", resourceCulture); } }
        public static string FileSettingPage_ClearCache { get { return ResourceManager.GetString("FileSettingPage_ClearCache", resourceCulture); } }
        public static string DownloadGamePage_TheDownloadTaskOfGameIsAlreadyRunning { get { return ResourceManager.GetString("DownloadGamePage_TheDownloadTaskOfGameIsAlreadyRunning", resourceCulture); } }
        public static string DownloadGamePage_TheFolderDoesNotExist { get { return ResourceManager.GetString("DownloadGamePage_TheFolderDoesNotExist", resourceCulture); } }
        public static string AppearanceSettingPage_BetterExperience { get { return ResourceManager.GetString("AppearanceSettingPage_BetterExperience", resourceCulture); } }
        public static string AppearanceSettingPage_TransparencyEffects { get { return ResourceManager.GetString("AppearanceSettingPage_TransparencyEffects", resourceCulture); } }
        public static string AppearanceSettingPage_AnimationEffects { get { return ResourceManager.GetString("AppearanceSettingPage_AnimationEffects", resourceCulture); } }
        public static string GachaLogPage_AlwaysFailedToGetGachaRecords { get { return ResourceManager.GetString("GachaLogPage_AlwaysFailedToGetGachaRecords", resourceCulture); } }
        public static string AboutSettingPage_VerifyFileIntegrity { get { return ResourceManager.GetString("AboutSettingPage_VerifyFileIntegrity", resourceCulture); } }
        public static string AboutSettingPage_VerifyFailed { get { return ResourceManager.GetString("AboutSettingPage_VerifyFailed", resourceCulture); } }
        public static string AboutSettingPage_CurrentVersionIsNotTheLatestVersion { get { return ResourceManager.GetString("AboutSettingPage_CurrentVersionIsNotTheLatestVersion", resourceCulture); } }
        public static string AboutSettingPage_ClickButtonToRepairFiles { get { return ResourceManager.GetString("AboutSettingPage_ClickButtonToRepairFiles", resourceCulture); } }
        public static string AboutSettingPage_RepairFiles { get { return ResourceManager.GetString("AboutSettingPage_RepairFiles", resourceCulture); } }
        public static string AboutSettingPage_VerifySuccessfully { get { return ResourceManager.GetString("AboutSettingPage_VerifySuccessfully", resourceCulture); } }
        public static string DownloadGamePage_0FilesVerifyFailed { get { return ResourceManager.GetString("DownloadGamePage_0FilesVerifyFailed", resourceCulture); } }
        public static string GachaLogPage_ShowChronicledWish { get { return ResourceManager.GetString("GachaLogPage_ShowChronicledWish", resourceCulture); } }
        public static string CloudGameGachaWindow_OpenTheGachaRecordsPageInGameAndThenClickTheButtonOnTheRight { get { return ResourceManager.GetString("CloudGameGachaWindow_OpenTheGachaRecordsPageInGameAndThenClickTheButtonOnTheRight", resourceCulture); } }
        public static string GachaLogPage_ViaCloudGame { get { return ResourceManager.GetString("GachaLogPage_ViaCloudGame", resourceCulture); } }
        public static string GameBizSelector_AutoSearch { get { return ResourceManager.GetString("GameBizSelector_AutoSearch", resourceCulture); } }
        public static string GachaLogService_SignalSearchRecords { get { return ResourceManager.GetString("GachaLogService_SignalSearchRecords", resourceCulture); } }
        public static string Common_Change { get { return ResourceManager.GetString("Common_Change", resourceCulture); } }
        public static string DownloadGamePage_Paused { get { return ResourceManager.GetString("DownloadGamePage_Paused", resourceCulture); } }
        public static string Common_Restart { get { return ResourceManager.GetString("Common_Restart", resourceCulture); } }
        public static string DeleteGachaLogDialog_BeginTime { get { return ResourceManager.GetString("DeleteGachaLogDialog_BeginTime", resourceCulture); } }
        public static string DeleteGachaLogDialog_EndTime { get { return ResourceManager.GetString("DeleteGachaLogDialog_EndTime", resourceCulture); } }
        public static string DeleteGachaLogDialog_DeleteGachaRecordsForASpecificTimePeriod { get { return ResourceManager.GetString("DeleteGachaLogDialog_DeleteGachaRecordsForASpecificTimePeriod", resourceCulture); } }
        public static string DeleteGachaLogDialog_6MonthsDeletingWarning { get { return ResourceManager.GetString("DeleteGachaLogDialog_6MonthsDeletingWarning", resourceCulture); } }
        public static string DeleteGachaLogDialog_ThisAccountHas0GachaRecordS { get { return ResourceManager.GetString("DeleteGachaLogDialog_ThisAccountHas0GachaRecordS", resourceCulture); } }
        public static string DeleteGachaLogDialog_TheSelectedTimePeriodIncludes0GachaRecords { get { return ResourceManager.GetString("DeleteGachaLogDialog_TheSelectedTimePeriodIncludes0GachaRecords", resourceCulture); } }
        public static string GachaLogPage_DeleteAll { get { return ResourceManager.GetString("GachaLogPage_DeleteAll", resourceCulture); } }
        public static string GachaLogPage_SpecificTimePeriod { get { return ResourceManager.GetString("GachaLogPage_SpecificTimePeriod", resourceCulture); } }


        public static string SettingPage_General { get { return ResourceManager.GetString("SettingPage_General", resourceCulture); } }
        public static string SettingPage_ForABetterExperiencePleaseEnableTheFollowingFeaturesInSystemSettings { get { return ResourceManager.GetString("SettingPage_ForABetterExperiencePleaseEnableTheFollowingFeaturesInSystemSettings", resourceCulture); } }
        public static string Common_WebView2ComponentInitializationFailed { get { return ResourceManager.GetString("Common_WebView2ComponentInitializationFailed", resourceCulture); } }
        public static string Common_Error { get { return ResourceManager.GetString("Common_Error", resourceCulture); } }
        public static string SettingPage_RunService { get { return ResourceManager.GetString("SettingPage_RunService", resourceCulture); } }
        public static string SettingPage_StopService { get { return ResourceManager.GetString("SettingPage_StopService", resourceCulture); } }

        public static string CloudGameButton_CloudGame { get { return ResourceManager.GetString("CloudGameButton_CloudGame", resourceCulture); } }
        public static string GameAccountSwitcher_TheCurrentlyLoggedInAccountIsNotSaved { get { return ResourceManager.GetString("GameAccountSwitcher_TheCurrentlyLoggedInAccountIsNotSaved", resourceCulture); } }
        public static string GachaImportAndExportWindow_Export { get { return ResourceManager.GetString("GachaImportAndExportWindow_Export", resourceCulture); } }
        public static string GachaImportAndExportWindow_SelectTheGachaRecordsToExport { get { return ResourceManager.GetString("GachaImportAndExportWindow_SelectTheGachaRecordsToExport", resourceCulture); } }
        public static string GachaImportAndExportWindow_TheLastGachaPull { get { return ResourceManager.GetString("GachaImportAndExportWindow_TheLastGachaPull", resourceCulture); } }
        public static string GachaImportAndExportWindow_Count { get { return ResourceManager.GetString("GachaImportAndExportWindow_Count", resourceCulture); } }
        public static string GachaImportAndExportWindow_TimeServerTimeZone { get { return ResourceManager.GetString("GachaImportAndExportWindow_TimeServerTimeZone", resourceCulture); } }
        public static string GachaImportAndExportWindow_Name { get { return ResourceManager.GetString("GachaImportAndExportWindow_Name", resourceCulture); } }
        public static string GachaImportAndExportWindow_SelectTheFileToImport { get { return ResourceManager.GetString("GachaImportAndExportWindow_SelectTheFileToImport", resourceCulture); } }
        public static string GachaImportAndExportWindow_Import { get { return ResourceManager.GetString("GachaImportAndExportWindow_Import", resourceCulture); } }
        public static string GachaImportAndExportWindow_TimeZoneOffsetWarning { get { return ResourceManager.GetString("GachaImportAndExportWindow_TimeZoneOffsetWarning", resourceCulture); } }
        public static string GachaImportAndExportWindow_TimeZoneOffset { get { return ResourceManager.GetString("GachaImportAndExportWindow_TimeZoneOffset", resourceCulture); } }
        public static string GachaImportAndExportWindow_OffsetTime { get { return ResourceManager.GetString("GachaImportAndExportWindow_OffsetTime", resourceCulture); } }
        public static string GachaImportAndExportWindow_SelectFile { get { return ResourceManager.GetString("GachaImportAndExportWindow_SelectFile", resourceCulture); } }
        public static string Common_Disabled { get { return ResourceManager.GetString("Common_Disabled", resourceCulture); } }
        public static string Common_Enabled { get { return ResourceManager.GetString("Common_Enabled", resourceCulture); } }
        public static string ClearedAt { get { return ResourceManager.GetString("ClearedAt", resourceCulture); } }
        public static string GachaLogPage_ImportAndExport { get { return ResourceManager.GetString("GachaLogPage_ImportAndExport", resourceCulture); } }
        public static string GachaLogPage_HideGachaBanners { get { return ResourceManager.GetString("GachaLogPage_HideGachaBanners", resourceCulture); } }
        public static string Common_RestoreDefaults { get { return ResourceManager.GetString("Common_RestoreDefaults", resourceCulture); } }
        public static string MainView_CheckSystemProxy_SystemProxyIsEnabled { get { return ResourceManager.GetString("MainView_CheckSystemProxy_SystemProxyIsEnabled", resourceCulture); } }
        public static string ScreenCaptureInfoWindow_ScreenshotSaved { get { return ResourceManager.GetString("ScreenCaptureInfoWindow_ScreenshotSaved", resourceCulture); } }
        public static string ScreenshotPage_ManageScreenshotFolders { get { return ResourceManager.GetString("ScreenshotPage_ManageScreenshotFolders", resourceCulture); } }
        public static string ScreenshotFolderManageDialog_AddFolder { get { return ResourceManager.GetString("ScreenshotFolderManageDialog_AddFolder", resourceCulture); } }
        public static string ScreenshotFolderManageDialog_BackingUp { get { return ResourceManager.GetString("ScreenshotFolderManageDialog_BackingUp", resourceCulture); } }
        public static string Common_Remove { get { return ResourceManager.GetString("Common_Remove", resourceCulture); } }
        public static string ScreenshotFolderManageDialog_FailedToBackupScreenshots { get { return ResourceManager.GetString("ScreenshotFolderManageDialog_FailedToBackupScreenshots", resourceCulture); } }
        public static string ScreenCaptureInfoWindow_ScreenshotFailed { get { return ResourceManager.GetString("ScreenCaptureInfoWindow_ScreenshotFailed", resourceCulture); } }
        public static string ScreenCaptureInfoWindow_CheckTheLogForMoreInformation { get { return ResourceManager.GetString("ScreenCaptureInfoWindow_CheckTheLogForMoreInformation", resourceCulture); } }
        public static string ScreenshotFolderManageDialog_ImagesFromTheFollowingFoldersWillBeDisplayedInTheGallery { get { return ResourceManager.GetString("ScreenshotFolderManageDialog_ImagesFromTheFollowingFoldersWillBeDisplayedInTheGallery", resourceCulture); } }
        public static string ImageViewWindow2_OpenInExplorer { get { return ResourceManager.GetString("ImageViewWindow2_OpenInExplorer", resourceCulture); } }
        public static string ImageViewWindow2_OpenWith { get { return ResourceManager.GetString("ImageViewWindow2_OpenWith", resourceCulture); } }
        public static string ImageViewWindow2_Previous { get { return ResourceManager.GetString("ImageViewWindow2_Previous", resourceCulture); } }
        public static string ImageViewWindow2_Next { get { return ResourceManager.GetString("ImageViewWindow2_Next", resourceCulture); } }
        public static string ImageViewWindow2_ShowGallery { get { return ResourceManager.GetString("ImageViewWindow2_ShowGallery", resourceCulture); } }
        public static string ImageViewWindow2_FitToWindow { get { return ResourceManager.GetString("ImageViewWindow2_FitToWindow", resourceCulture); } }
        public static string ImageViewWindow2_CopyFile { get { return ResourceManager.GetString("ImageViewWindow2_CopyFile", resourceCulture); } }
        public static string ImageViewWindow2_CopyPath { get { return ResourceManager.GetString("ImageViewWindow2_CopyPath", resourceCulture); } }
        public static string ImageViewWindow2_CopyImage { get { return ResourceManager.GetString("ImageViewWindow2_CopyImage", resourceCulture); } }
        public static string Common_Edit { get { return ResourceManager.GetString("Common_Edit", resourceCulture); } }
        public static string ImageViewWindow2_SaveAs { get { return ResourceManager.GetString("ImageViewWindow2_SaveAs", resourceCulture); } }
        public static string ImageViewWindow2_ImageInformation { get { return ResourceManager.GetString("ImageViewWindow2_ImageInformation", resourceCulture); } }
        public static string ImageViewWindow2_EditImage { get { return ResourceManager.GetString("ImageViewWindow2_EditImage", resourceCulture); } }
        public static string ImageViewWindow2_DisplayMode { get { return ResourceManager.GetString("ImageViewWindow2_DisplayMode", resourceCulture); } }
        public static string ImageViewWindow2_SDRMappedLuminance { get { return ResourceManager.GetString("ImageViewWindow2_SDRMappedLuminance", resourceCulture); } }
        public static string ImageViewWindow2_Auto { get { return ResourceManager.GetString("ImageViewWindow2_Auto", resourceCulture); } }
        public static string ImageViewWindow2_ExportImage { get { return ResourceManager.GetString("ImageViewWindow2_ExportImage", resourceCulture); } }
        public static string ImageViewWindow2_ToConvertAnHDRImageToSDRPleaseUseTheEditFeature { get { return ResourceManager.GetString("ImageViewWindow2_ToConvertAnHDRImageToSDRPleaseUseTheEditFeature", resourceCulture); } }
        public static string ImageViewWindow2_DeleteImageFile { get { return ResourceManager.GetString("ImageViewWindow2_DeleteImageFile", resourceCulture); } }
        public static string ImageViewWindow2_CopiedToClipboard { get { return ResourceManager.GetString("ImageViewWindow2_CopiedToClipboard", resourceCulture); } }
        public static string ImageViewWindow2_FileDoesNotExist { get { return ResourceManager.GetString("ImageViewWindow2_FileDoesNotExist", resourceCulture); } }
        public static string ImageViewWindow2_OpenWithDefaultApp { get { return ResourceManager.GetString("ImageViewWindow2_OpenWithDefaultApp", resourceCulture); } }
        public static string ImageViewWindow2_NoImageToDisplay { get { return ResourceManager.GetString("ImageViewWindow2_NoImageToDisplay", resourceCulture); } }
        public static string Common_OpenFiles { get { return ResourceManager.GetString("Common_OpenFiles", resourceCulture); } }
        public static string ImageViewWindow2_OpenNewFiles { get { return ResourceManager.GetString("ImageViewWindow2_OpenNewFiles", resourceCulture); } }
        public static string ImageViewWindow2_FailedToDisplayImage { get { return ResourceManager.GetString("ImageViewWindow2_FailedToDisplayImage", resourceCulture); } }
        public static string ImageViewWindow2_FailedToSaveImage { get { return ResourceManager.GetString("ImageViewWindow2_FailedToSaveImage", resourceCulture); } }
        public static string ImageViewWindow2_FailedToDeleteImageFile { get { return ResourceManager.GetString("ImageViewWindow2_FailedToDeleteImageFile", resourceCulture); } }
        public static string ImageViewWindow2_UnableToDeleteTheFile { get { return ResourceManager.GetString("ImageViewWindow2_UnableToDeleteTheFile", resourceCulture); } }
        public static string ImageViewWindow2_InsufficientPermissionsOrTheFileIsInUse { get { return ResourceManager.GetString("ImageViewWindow2_InsufficientPermissionsOrTheFileIsInUse", resourceCulture); } }
        public static string HotkeyInput_ClickToSetShortcutKeys { get { return ResourceManager.GetString("HotkeyInput_ClickToSetShortcutKeys", resourceCulture); } }
        public static string HotkeyInput_PressTheShortcutKeys { get { return ResourceManager.GetString("HotkeyInput_PressTheShortcutKeys", resourceCulture); } }
        public static string HotkeyManager_TheShortcutKeys0IsAlreadyInUse { get { return ResourceManager.GetString("HotkeyManager_TheShortcutKeys0IsAlreadyInUse", resourceCulture); } }
        public static string HotkeyManager_FailedToRegisterTheShortcutKeys0 { get { return ResourceManager.GetString("HotkeyManager_FailedToRegisterTheShortcutKeys0", resourceCulture); } }
        public static string HotkeyManager_TheShortcutKeys0IsAlreadyInUsePleaseModifyItInSettingsPage { get { return ResourceManager.GetString("HotkeyManager_TheShortcutKeys0IsAlreadyInUsePleaseModifyItInSettingsPage", resourceCulture); } }
        public static string HotkeyManager_FailedToRegisterTheShortcutKeys0PleaseRetryInSettingsPage { get { return ResourceManager.GetString("HotkeyManager_FailedToRegisterTheShortcutKeys0PleaseRetryInSettingsPage", resourceCulture); } }
        public static string ScreenshotSetting_ScreenshotShortcut { get { return ResourceManager.GetString("ScreenshotSetting_ScreenshotShortcut", resourceCulture); } }
        public static string HotkeySetting_OpenMainWindow { get { return ResourceManager.GetString("HotkeySetting_OpenMainWindow", resourceCulture); } }
        public static string HotkeySetting_FailedToRegisterTheShortcutKeys { get { return ResourceManager.GetString("HotkeySetting_FailedToRegisterTheShortcutKeys", resourceCulture); } }
        public static string ScreenshotSetting_TheBuiltInScreenshotFeatureWillSaveImagesToTheFollowingFolder { get { return ResourceManager.GetString("ScreenshotSetting_TheBuiltInScreenshotFeatureWillSaveImagesToTheFollowingFolder", resourceCulture); } }
        public static string Common_ChangeFolder { get { return ResourceManager.GetString("Common_ChangeFolder", resourceCulture); } }
        public static string HotkeySetting_SingleKeyShortcutsTips { get { return ResourceManager.GetString("HotkeySetting_SingleKeyShortcutsTips", resourceCulture); } }
        public static string SettingPage_KeyboardShortcuts { get { return ResourceManager.GetString("SettingPage_KeyboardShortcuts", resourceCulture); } }
        public static string SettingPage_ControllerEnhancement { get { return ResourceManager.GetString("SettingPage_ControllerEnhancement", resourceCulture); } }
        public static string ScreenshotSetting_TestScreenshot { get { return ResourceManager.GetString("ScreenshotSetting_TestScreenshot", resourceCulture); } }
        public static string ScreenshotSetting_AutoConvertToSDRImage { get { return ResourceManager.GetString("ScreenshotSetting_AutoConvertToSDRImage", resourceCulture); } }
        public static string ScreenshotSetting_WhenCapturingHDRImagesSDRVersionWillAlsoBeSaved { get { return ResourceManager.GetString("ScreenshotSetting_WhenCapturingHDRImagesSDRVersionWillAlsoBeSaved", resourceCulture); } }
        public static string ScreenshotSetting_ScreenshotFetureDescAndLimit { get { return ResourceManager.GetString("ScreenshotSetting_ScreenshotFetureDescAndLimit", resourceCulture); } }
        public static string ScreenshotSetting_ScreenshotWin10Limit { get { return ResourceManager.GetString("ScreenshotSetting_ScreenshotWin10Limit", resourceCulture); } }
        public static string ScreenshotSetting_ScreenshotWithGamepadSuggestion { get { return ResourceManager.GetString("ScreenshotSetting_ScreenshotWithGamepadSuggestion", resourceCulture); } }
        public static string ScreenshotSetting_AutoCopyScreenshotFile { get { return ResourceManager.GetString("ScreenshotSetting_AutoCopyScreenshotFile", resourceCulture); } }
        public static string ImageViewWindow2_CopyAsJPG { get { return ResourceManager.GetString("ImageViewWindow2_CopyAsJPG", resourceCulture); } }
        public static string ScreenshotPage_MultiSelect { get { return ResourceManager.GetString("ScreenshotPage_MultiSelect", resourceCulture); } }
        public static string ScreenshotPage_Total0Files { get { return ResourceManager.GetString("ScreenshotPage_Total0Files", resourceCulture); } }
        public static string ScreenshotSetting_OtherOptions { get { return ResourceManager.GetString("ScreenshotSetting_OtherOptions", resourceCulture); } }
        public static string ScreenshotSetting_Lossless { get { return ResourceManager.GetString("ScreenshotSetting_Lossless", resourceCulture); } }
        public static string ScreenshotSetting_FormatAndQuality { get { return ResourceManager.GetString("ScreenshotSetting_FormatAndQuality", resourceCulture); } }
        public static string ScreenCaptureInfoWindow_ProcessingImage { get { return ResourceManager.GetString("ScreenCaptureInfoWindow_ProcessingImage", resourceCulture); } }
        public static string ScreenshotPage_BatchConvert { get { return ResourceManager.GetString("ScreenshotPage_BatchConvert", resourceCulture); } }
        public static string ImageBatchConvertWindow_Quality { get { return ResourceManager.GetString("ImageBatchConvertWindow_Quality", resourceCulture); } }
        public static string ImageBatchConvertWindow_StartConvert { get { return ResourceManager.GetString("ImageBatchConvertWindow_StartConvert", resourceCulture); } }
        public static string Common_Clear { get { return ResourceManager.GetString("Common_Clear", resourceCulture); } }
        public static string ImageBatchConvertWindow_OutputFolder { get { return ResourceManager.GetString("ImageBatchConvertWindow_OutputFolder", resourceCulture); } }
        public static string ImageBatchConvertWindow_OriginalFileFolder { get { return ResourceManager.GetString("ImageBatchConvertWindow_OriginalFileFolder", resourceCulture); } }
        public static string ImageBatchConvertWindow_SameAsOriginalFileFormat { get { return ResourceManager.GetString("ImageBatchConvertWindow_SameAsOriginalFileFormat", resourceCulture); } }
        public static string ImageBatchConvertWindow_SelectOutputFormat { get { return ResourceManager.GetString("ImageBatchConvertWindow_SelectOutputFormat", resourceCulture); } }
        public static string ImageBatchConvertWindow_NoReadOrWritePermission { get { return ResourceManager.GetString("ImageBatchConvertWindow_NoReadOrWritePermission", resourceCulture); } }
        public static string ImageBatchConvertWindow_ConvertFailed { get { return ResourceManager.GetString("ImageBatchConvertWindow_ConvertFailed", resourceCulture); } }
        public static string ImageBatchConvertWindow_IfOutputFileExists { get { return ResourceManager.GetString("ImageBatchConvertWindow_IfOutputFileExists", resourceCulture); } }
        public static string ImageBatchConvertWindow_SkipDefault { get { return ResourceManager.GetString("ImageBatchConvertWindow_SkipDefault", resourceCulture); } }
        public static string ImageBatchConvertWindow_Overwrite { get { return ResourceManager.GetString("ImageBatchConvertWindow_Overwrite", resourceCulture); } }
        public static string ImageBatchConvertWindow_Rename { get { return ResourceManager.GetString("ImageBatchConvertWindow_Rename", resourceCulture); } }
        public static string Common_Success { get { return ResourceManager.GetString("Common_Success", resourceCulture); } }
        public static string Common_Failed { get { return ResourceManager.GetString("Common_Failed", resourceCulture); } }
        public static string ImageBatchConvertWindow_ImageBatchConvert { get { return ResourceManager.GetString("ImageBatchConvertWindow_ImageBatchConvert", resourceCulture); } }
        public static string ScreenshotSetting_ClearThumbnailCache { get { return ResourceManager.GetString("ScreenshotSetting_ClearThumbnailCache", resourceCulture); } }
        public static string ScreenshotSetting_ClearSuccessfully { get { return ResourceManager.GetString("ScreenshotSetting_ClearSuccessfully", resourceCulture); } }
        public static string ScreenshotSetting_ClearFailed { get { return ResourceManager.GetString("ScreenshotSetting_ClearFailed", resourceCulture); } }
        public static string ScreenshotSetting_HighQualityAVIFAndJPEGXLImageFormatsSaveApproximately85OfStorageSpace { get { return ResourceManager.GetString("ScreenshotSetting_HighQualityAVIFAndJPEGXLImageFormatsSaveApproximately85OfStorageSpace", resourceCulture); } }
        public static string Common_CopiedToClipboard { get { return ResourceManager.GetString("Common_CopiedToClipboard", resourceCulture); } }
        public static string GenshinBeyondGachaPage_MiliastraWonderlandOde { get { return ResourceManager.GetString("GenshinBeyondGachaPage_MiliastraWonderlandOde", resourceCulture); } }
        public static string ItIsRecommendedToInstallTheVP9VideoExtensionsToReduceCPUUsage { get { return ResourceManager.GetString("ItIsRecommendedToInstallTheVP9VideoExtensionsToReduceCPUUsage", resourceCulture); } }
        public static string ChallengePeakPage_ChallengeAttempts { get { return ResourceManager.GetString("ChallengePeakPage_ChallengeAttempts", resourceCulture); } }
        public static string ChallengePeakPage_KingInCheckStageRecords { get { return ResourceManager.GetString("ChallengePeakPage_KingInCheckStageRecords", resourceCulture); } }
        public static string ChallengePeakPage_Cleared { get { return ResourceManager.GetString("ChallengePeakPage_Cleared", resourceCulture); } }
        public static string ChallengePeakPage_NoClearanceRecords { get { return ResourceManager.GetString("ChallengePeakPage_NoClearanceRecords", resourceCulture); } }
        public static string ChallengePeakPage_KnightStageRecords { get { return ResourceManager.GetString("ChallengePeakPage_KnightStageRecords", resourceCulture); } }
        public static string AboutSetting_UpdatedToTheLatestVersion { get { return ResourceManager.GetString("AboutSetting_UpdatedToTheLatestVersion", resourceCulture); } }
        public static string BackgroundViewPage_DeleteDuplicateFiles { get { return ResourceManager.GetString("BackgroundViewPage_DeleteDuplicateFiles", resourceCulture); } }
        public static string BackgroundViewPage_0DuplicateFileSHasBeenDeleted { get { return ResourceManager.GetString("BackgroundViewPage_0DuplicateFileSHasBeenDeleted", resourceCulture); } }
        public static string Common_All { get { return ResourceManager.GetString("Common_All", resourceCulture); } }
        public static string Common_Video { get { return ResourceManager.GetString("Common_Video", resourceCulture); } }
        public static string Common_Time { get { return ResourceManager.GetString("Common_Time", resourceCulture); } }
        public static string Common_FileSize { get { return ResourceManager.GetString("Common_FileSize", resourceCulture); } }
        public static string Common_Filter { get { return ResourceManager.GetString("Common_Filter", resourceCulture); } }
        public static string Common_Sort { get { return ResourceManager.GetString("Common_Sort", resourceCulture); } }
        public static string BackgroundViewPage_DeleteDuplicateFilesTip { get { return ResourceManager.GetString("BackgroundViewPage_DeleteDuplicateFilesTip", resourceCulture); } }
        public static string BackgroundViewPage_VP9VideoExtensionsTip { get { return ResourceManager.GetString("BackgroundViewPage_VP9VideoExtensionsTip", resourceCulture); } }
        public static string AppBackground_ImageDecodingFailed { get { return ResourceManager.GetString("AppBackground_ImageDecodingFailed", resourceCulture); } }
        public static string AppBackground_PleaseInstallTheWebPImageExtension { get { return ResourceManager.GetString("AppBackground_PleaseInstallTheWebPImageExtension", resourceCulture); } }
        public static string AppBackground_VideoDecodingFailed { get { return ResourceManager.GetString("AppBackground_VideoDecodingFailed", resourceCulture); } }
        public static string AppBackground_VideoDecodingFailedPleaseInstallTheVP9VideoExtensions { get { return ResourceManager.GetString("AppBackground_VideoDecodingFailedPleaseInstallTheVP9VideoExtensions", resourceCulture); } }
        public static string AppConfig_AnUnknownIssueOccurredDuringInitialization { get { return ResourceManager.GetString("AppConfig_AnUnknownIssueOccurredDuringInitialization", resourceCulture); } }
        public static string NoPermissionWindow_NoPermissionToFolderRestartOrClose { get { return ResourceManager.GetString("NoPermissionWindow_NoPermissionToFolderRestartOrClose", resourceCulture); } }
        public static string NoPermissionWindow_RestartAsAdministrator { get { return ResourceManager.GetString("NoPermissionWindow_RestartAsAdministrator", resourceCulture); } }
        public static string LauncherPage_ConfirmDelete { get { return ResourceManager.GetString("LauncherPage_ConfirmDelete", resourceCulture); } }
    
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string Common_ConfirmDelete {
            get {
                return ResourceManager.GetString("Common_ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Glowworm.
        /// </summary>
        public static string Common_Glowworm {
            get {
                return ResourceManager.GetString("Common_Glowworm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        public static string Common_Uid {
            get {
                return ResourceManager.GetString("Common_Uid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to up!.
        /// </summary>
        public static string GachaStatsCard_Up {
            get {
                return ResourceManager.GetString("GachaStatsCard_Up", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event Ode.
        /// </summary>
        public static string GachaType_EventOde {
            get {
                return ResourceManager.GetString("GachaType_EventOde", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standard Ode.
        /// </summary>
        public static string GachaType_StandardOde {
            get {
                return ResourceManager.GetString("GachaType_StandardOde", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to Glowworm! We will now check your available games..
        /// </summary>
        public static string MainView_WelcomeContent {
            get {
                return ResourceManager.GetString("MainView_WelcomeContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to Glowworm.
        /// </summary>
        public static string MainView_WelcomeTitle {
            get {
                return ResourceManager.GetString("MainView_WelcomeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rescan Game Directories.
        /// </summary>
        public static string SettingPage_RescanGameDirectories {
            get {
                return ResourceManager.GetString("SettingPage_RescanGameDirectories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A rework of Starward Launcher developed by Scighost, reworked by Studio Butter, all rights reserved..
        /// </summary>
        public static string AboutSettingPage_Description {
            get {
                return ResourceManager.GetString("AboutSettingPage_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to via Cloud Game (Web).
        /// </summary>
        public static string GachaLogPage_ViaCloudGameWeb {
            get {
                return ResourceManager.GetString("GachaLogPage_ViaCloudGameWeb", resourceCulture);
            }
        }
    }
}