//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glowworm.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glowworm.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated to the latest version..
        /// </summary>
        public static string AboutSetting_UpdatedToTheLatestVersion {
            get {
                return ResourceManager.GetString("AboutSetting_UpdatedToTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rework of Starward Launcher originally developed by Scighost, reworked by Studio Butter, all rights reserved..
        /// </summary>
        public static string AboutSettingPage_Description {
            get {
                return ResourceManager.GetString("AboutSettingPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string AboutSettingPage_Links {
            get {
                return ResourceManager.GetString("AboutSettingPage_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown issue occurred during initialization..
        /// </summary>
        public static string AppConfig_AnUnknownIssueOccurredDuringInitialization {
            get {
                return ResourceManager.GetString("AppConfig_AnUnknownIssueOccurredDuringInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation effects.
        /// </summary>
        public static string AppearanceSettingPage_AnimationEffects {
            get {
                return ResourceManager.GetString("AppearanceSettingPage_AnimationEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us translate Glowworm.
        /// </summary>
        public static string AppearanceSettingPage_HelpUsTranslateGlowworm {
            get {
                return ResourceManager.GetString("AppearanceSettingPage_HelpUsTranslateGlowworm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency effects.
        /// </summary>
        public static string AppearanceSettingPage_TransparencyEffects {
            get {
                return ResourceManager.GetString("AppearanceSettingPage_TransparencyEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get Profile Pictures, ensure you have taken on in-game and save it before getting the pictures.
        /// </summary>
        public static string BeyondProfilePicturePage_FolderNotFound {
            get {
                return ResourceManager.GetString("BeyondProfilePicturePage_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Profile Pictures.
        /// </summary>
        public static string BeyondProfilePicturePage_GetProfilePictures {
            get {
                return ResourceManager.GetString("BeyondProfilePicturePage_GetProfilePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miliastra Profile Pictures.
        /// </summary>
        public static string BeyondProfilePicturePage_MiliastraProfilePictures {
            get {
                return ResourceManager.GetString("BeyondProfilePicturePage_MiliastraProfilePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image found.
        /// </summary>
        public static string BeyondProfilePicturePage_NoImage {
            get {
                return ResourceManager.GetString("BeyondProfilePicturePage_NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string BeyondProfilePicturePage_SaveAs {
            get {
                return ResourceManager.GetString("BeyondProfilePicturePage_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Game.
        /// </summary>
        public static string CloudGameButton_CloudGame {
            get {
                return ResourceManager.GetString("CloudGameButton_CloudGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the gacha records page in game, and then click the button on the right..
        /// </summary>
        public static string CloudGameGachaWindow_OpenTheGachaRecordsPageInGameAndThenClickTheButtonOnTheRight {
            get {
                return ResourceManager.GetString("CloudGameGachaWindow_OpenTheGachaRecordsPageInGameAndThenClickTheButtonOnTheRight" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Common_Accept {
            get {
                return ResourceManager.GetString("Common_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Error.
        /// </summary>
        public static string Common_AccountError {
            get {
                return ResourceManager.GetString("Common_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Common_All {
            get {
                return ResourceManager.GetString("Common_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Common_Attention {
            get {
                return ResourceManager.GetString("Common_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Common_Change {
            get {
                return ResourceManager.GetString("Common_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Folder.
        /// </summary>
        public static string Common_ChangeFolder {
            get {
                return ResourceManager.GetString("Common_ChangeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string Common_ConfirmDelete {
            get {
                return ResourceManager.GetString("Common_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Common_Continue {
            get {
                return ResourceManager.GetString("Common_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard..
        /// </summary>
        public static string Common_CopiedToClipboard {
            get {
                return ResourceManager.GetString("Common_CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Common_Copy {
            get {
                return ResourceManager.GetString("Common_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Common_Disabled {
            get {
                return ResourceManager.GetString("Common_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Common_Disclaimer {
            get {
                return ResourceManager.GetString("Common_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Common_Enabled {
            get {
                return ResourceManager.GetString("Common_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Common_Exit {
            get {
                return ResourceManager.GetString("Common_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Common_Failed {
            get {
                return ResourceManager.GetString("Common_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string Common_FileSize {
            get {
                return ResourceManager.GetString("Common_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Common_Filter {
            get {
                return ResourceManager.GetString("Common_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glowworm.
        /// </summary>
        public static string Common_Glowworm {
            get {
                return ResourceManager.GetString("Common_Glowworm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Common_Hide {
            get {
                return ResourceManager.GetString("Common_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string Common_NetworkError {
            get {
                return ResourceManager.GetString("Common_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Common_Open {
            get {
                return ResourceManager.GetString("Common_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Files.
        /// </summary>
        public static string Common_OpenFiles {
            get {
                return ResourceManager.GetString("Common_OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Common_Refresh {
            get {
                return ResourceManager.GetString("Common_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Common_Reject {
            get {
                return ResourceManager.GetString("Common_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Common_Restart {
            get {
                return ResourceManager.GetString("Common_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        public static string Common_RestoreDefaults {
            get {
                return ResourceManager.GetString("Common_RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Common_Select {
            get {
                return ResourceManager.GetString("Common_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Common_Setting {
            get {
                return ResourceManager.GetString("Common_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Common_Sort {
            get {
                return ResourceManager.GetString("Common_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Common_Start {
            get {
                return ResourceManager.GetString("Common_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Common_Success {
            get {
                return ResourceManager.GetString("Common_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Common_Summary {
            get {
                return ResourceManager.GetString("Common_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Common_Time {
            get {
                return ResourceManager.GetString("Common_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        public static string Common_Uid {
            get {
                return ResourceManager.GetString("Common_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Common_Video {
            get {
                return ResourceManager.GetString("Common_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 component initialization failed..
        /// </summary>
        public static string Common_WebView2ComponentInitializationFailed {
            get {
                return ResourceManager.GetString("Common_WebView2ComponentInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The selected time period includes gacha records from more than 6-12 months ago, which cannot be retrieved after deleting..
        /// </summary>
        public static string DeleteGachaLogDialog_6MonthsDeletingWarning {
            get {
                return ResourceManager.GetString("DeleteGachaLogDialog_6MonthsDeletingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Time.
        /// </summary>
        public static string DeleteGachaLogDialog_BeginTime {
            get {
                return ResourceManager.GetString("DeleteGachaLogDialog_BeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete gacha records for a specific time period.
        /// </summary>
        public static string DeleteGachaLogDialog_DeleteGachaRecordsForASpecificTimePeriod {
            get {
                return ResourceManager.GetString("DeleteGachaLogDialog_DeleteGachaRecordsForASpecificTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string DeleteGachaLogDialog_EndTime {
            get {
                return ResourceManager.GetString("DeleteGachaLogDialog_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected time period includes {0} gacha records..
        /// </summary>
        public static string DeleteGachaLogDialog_TheSelectedTimePeriodIncludes0GachaRecords {
            get {
                return ResourceManager.GetString("DeleteGachaLogDialog_TheSelectedTimePeriodIncludes0GachaRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has {0} gacha record(s)..
        /// </summary>
        public static string DeleteGachaLogDialog_ThisAccountHas0GachaRecordS {
            get {
                return ResourceManager.GetString("DeleteGachaLogDialog_ThisAccountHas0GachaRecordS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string FileSettingPage_Browser {
            get {
                return ResourceManager.GetString("FileSettingPage_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string FileSettingPage_Cache {
            get {
                return ResourceManager.GetString("FileSettingPage_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string FileSettingPage_ClearCache {
            get {
                return ResourceManager.GetString("FileSettingPage_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Folder.
        /// </summary>
        public static string FileSettingPage_DataFolder {
            get {
                return ResourceManager.GetString("FileSettingPage_DataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal data is stored in the folder below. It is very important, please do not delete it casually..
        /// </summary>
        public static string FileSettingPage_DataFolderIsImportant {
            get {
                return ResourceManager.GetString("FileSettingPage_DataFolderIsImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string FileSettingPage_Image {
            get {
                return ResourceManager.GetString("FileSettingPage_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string FileSettingPage_Log {
            get {
                return ResourceManager.GetString("FileSettingPage_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder is not writable: {0}.
        /// </summary>
        public static string FileSettingPage_SelectedFolderNotWritable {
            get {
                return ResourceManager.GetString("FileSettingPage_SelectedFolderNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string GachaImportAndExportWindow_Count {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string GachaImportAndExportWindow_Export {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string GachaImportAndExportWindow_Import {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GachaImportAndExportWindow_Name {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Time.
        /// </summary>
        public static string GachaImportAndExportWindow_OffsetTime {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_OffsetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string GachaImportAndExportWindow_SelectFile {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to import..
        /// </summary>
        public static string GachaImportAndExportWindow_SelectTheFileToImport {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_SelectTheFileToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the gacha records to export..
        /// </summary>
        public static string GachaImportAndExportWindow_SelectTheGachaRecordsToExport {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_SelectTheGachaRecordsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Gacha Pull.
        /// </summary>
        public static string GachaImportAndExportWindow_TheLastGachaPull {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_TheLastGachaPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (Server Time Zone).
        /// </summary>
        public static string GachaImportAndExportWindow_TimeServerTimeZone {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_TimeServerTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone Offset.
        /// </summary>
        public static string GachaImportAndExportWindow_TimeZoneOffset {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_TimeZoneOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before importing, please ensure that the time of the last gacha pull matches the time displayed in the game. If they do not match, please adjust the time zone offset..
        /// </summary>
        public static string GachaImportAndExportWindow_TimeZoneOffsetWarning {
            get {
                return ResourceManager.GetString("GachaImportAndExportWindow_TimeZoneOffsetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of {0} gacha records has been changed to ({1})..
        /// </summary>
        public static string GachaLogPage_0GachaItemsHaveBeenChangedToLanguage1 {
            get {
                return ResourceManager.GetString("GachaLogPage_0GachaItemsHaveBeenChangedToLanguage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authkey Timeout always occurs?.
        /// </summary>
        public static string GachaLogPage_AuthkeyTimeoutAlwaysOccurs {
            get {
                return ResourceManager.GetString("GachaLogPage_AuthkeyTimeoutAlwaysOccurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find saved URL of UID {0}..
        /// </summary>
        public static string GachaLogPage_CannotFindSavedURLOfUid {
            get {
                return ResourceManager.GetString("GachaLogPage_CannotFindSavedURLOfUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find URL, please open the gacha records history page in game..
        /// </summary>
        public static string GachaLogPage_CannotFindURL {
            get {
                return ResourceManager.GetString("GachaLogPage_CannotFindURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear URL Cache Files.
        /// </summary>
        public static string GachaLogPage_ClearURLCacheFiles {
            get {
                return ResourceManager.GetString("GachaLogPage_ClearURLCacheFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL.
        /// </summary>
        public static string GachaLogPage_CopyURL {
            get {
                return ResourceManager.GetString("GachaLogPage_CopyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string GachaLogPage_DeleteAll {
            get {
                return ResourceManager.GetString("GachaLogPage_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} gacha record(s) of UID {1}..
        /// </summary>
        public static string GachaLogPage_DeletedGachaRecordsOfUid {
            get {
                return ResourceManager.GetString("GachaLogPage_DeletedGachaRecordsOfUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All gacha records of UID {0} will be deleted, and you won&apos;t able to undo this operation..
        /// </summary>
        public static string GachaLogPage_DeleteGachaRecordsWarning {
            get {
                return ResourceManager.GetString("GachaLogPage_DeleteGachaRecordsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Records.
        /// </summary>
        public static string GachaLogPage_DeleteRecords {
            get {
                return ResourceManager.GetString("GachaLogPage_DeleteRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as.
        /// </summary>
        public static string GachaLogPage_ExportAs {
            get {
                return ResourceManager.GetString("GachaLogPage_ExportAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the language of gacha records, such as en-us..
        /// </summary>
        public static string GachaLogPage_GachaLanguageDesc {
            get {
                return ResourceManager.GetString("GachaLogPage_GachaLanguageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not installed.
        /// </summary>
        public static string GachaLogPage_GameNotInstalled {
            get {
                return ResourceManager.GetString("GachaLogPage_GameNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Gacha Banners.
        /// </summary>
        public static string GachaLogPage_HideGachaBanners {
            get {
                return ResourceManager.GetString("GachaLogPage_HideGachaBanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &amp; Export.
        /// </summary>
        public static string GachaLogPage_ImportAndExport {
            get {
                return ResourceManager.GetString("GachaLogPage_ImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from JSON.
        /// </summary>
        public static string GachaLogPage_ImportFromJson {
            get {
                return ResourceManager.GetString("GachaLogPage_ImportFromJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input URL.
        /// </summary>
        public static string GachaLogPage_InputURL {
            get {
                return ResourceManager.GetString("GachaLogPage_InputURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string GachaLogPage_Language {
            get {
                return ResourceManager.GetString("GachaLogPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Gacha Records.
        /// </summary>
        public static string GachaLogPage_NoGachaRecords {
            get {
                return ResourceManager.GetString("GachaLogPage_NoGachaRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled.
        /// </summary>
        public static string GachaLogPage_OperationCanceled {
            get {
                return ResourceManager.GetString("GachaLogPage_OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string GachaLogPage_OtherSettings {
            get {
                return ResourceManager.GetString("GachaLogPage_OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open the gacha records page in game and try again..
        /// </summary>
        public static string GachaLogPage_PleaseOpenTheGachaRecordsPageInGameAndTryAgain {
            get {
                return ResourceManager.GetString("GachaLogPage_PleaseOpenTheGachaRecordsPageInGameAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Time Period.
        /// </summary>
        public static string GachaLogPage_SpecificTimePeriod {
            get {
                return ResourceManager.GetString("GachaLogPage_SpecificTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update (All).
        /// </summary>
        public static string GachaLogPage_UpdateAll {
            get {
                return ResourceManager.GetString("GachaLogPage_UpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Records.
        /// </summary>
        public static string GachaLogPage_UpdateRecords {
            get {
                return ResourceManager.GetString("GachaLogPage_UpdateRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update (Saved URL).
        /// </summary>
        public static string GachaLogPage_UpdateSavedURL {
            get {
                return ResourceManager.GetString("GachaLogPage_UpdateSavedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via Cloud Game.
        /// </summary>
        public static string GachaLogPage_ViaCloudGame {
            get {
                return ResourceManager.GetString("GachaLogPage_ViaCloudGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via Cloud Game (Web).
        /// </summary>
        public static string GachaLogPage_ViaCloudGameWeb {
            get {
                return ResourceManager.GetString("GachaLogPage_ViaCloudGameWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting {0} with page {1}.
        /// </summary>
        public static string GachaLogService_GetGachaProgressText {
            get {
                return ResourceManager.GetString("GachaLogService_GetGachaProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got {0} record(s), added {1} record(s)..
        /// </summary>
        public static string GachaLogService_GetGachaResult {
            get {
                return ResourceManager.GetString("GachaLogService_GetGachaResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting UID.
        /// </summary>
        public static string GachaLogService_GettingUid {
            get {
                return ResourceManager.GetString("GachaLogService_GettingUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Search Records.
        /// </summary>
        public static string GachaLogService_SignalSearchRecords {
            get {
                return ResourceManager.GetString("GachaLogService_SignalSearchRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has no gacha records in the last 6-12 months..
        /// </summary>
        public static string GachaLogService_ThisAccountHasNoGachaRecordsInTheLast6Months {
            get {
                return ResourceManager.GetString("GachaLogService_ThisAccountHasNoGachaRecordsInTheLast6Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp Records.
        /// </summary>
        public static string GachaLogService_WarpRecords {
            get {
                return ResourceManager.GetString("GachaLogService_WarpRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish Records.
        /// </summary>
        public static string GachaLogService_WishRecords {
            get {
                return ResourceManager.GetString("GachaLogService_WishRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string GachaStatsCard_Average {
            get {
                return ResourceManager.GetString("GachaStatsCard_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pity.
        /// </summary>
        public static string GachaStatsCard_Pity {
            get {
                return ResourceManager.GetString("GachaStatsCard_Pity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string GachaStatsCard_Stats {
            get {
                return ResourceManager.GetString("GachaStatsCard_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up!.
        /// </summary>
        public static string GachaStatsCard_Up {
            get {
                return ResourceManager.GetString("GachaStatsCard_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Ode.
        /// </summary>
        public static string GachaType_EventOde {
            get {
                return ResourceManager.GetString("GachaType_EventOde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Ode.
        /// </summary>
        public static string GachaType_StandardOde {
            get {
                return ResourceManager.GetString("GachaType_StandardOde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Search.
        /// </summary>
        public static string GameBizSelector_AutoSearch {
            get {
                return ResourceManager.GetString("GameBizSelector_AutoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miliastra Wonderland Ode.
        /// </summary>
        public static string GenshinBeyondGachaPage_MiliastraWonderlandOde {
            get {
                return ResourceManager.GetString("GenshinBeyondGachaPage_MiliastraWonderlandOde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import {0} wish record(s) successfully..
        /// </summary>
        public static string GenshinGachaService_ImportWishRecordsSuccessfully {
            get {
                return ResourceManager.GetString("GenshinGachaService_ImportWishRecordsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Set Shortcut Keys.
        /// </summary>
        public static string HotkeyInput_ClickToSetShortcutKeys {
            get {
                return ResourceManager.GetString("HotkeyInput_ClickToSetShortcutKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the Shortcut Keys.
        /// </summary>
        public static string HotkeyInput_PressTheShortcutKeys {
            get {
                return ResourceManager.GetString("HotkeyInput_PressTheShortcutKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you register single-key shortcuts (F1-F12), you need to run Glowworm with administrator privileges; otherwise, the shortcuts may not work in the game..
        /// </summary>
        public static string HotkeySetting_SingleKeyShortcutsTips {
            get {
                return ResourceManager.GetString("HotkeySetting_SingleKeyShortcutsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert failed.
        /// </summary>
        public static string ImageBatchConvertWindow_ConvertFailed {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_ConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Output File Exists.
        /// </summary>
        public static string ImageBatchConvertWindow_IfOutputFileExists {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_IfOutputFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Batch Convert.
        /// </summary>
        public static string ImageBatchConvertWindow_ImageBatchConvert {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_ImageBatchConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No read or write permission.
        /// </summary>
        public static string ImageBatchConvertWindow_NoReadOrWritePermission {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_NoReadOrWritePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original File Folder.
        /// </summary>
        public static string ImageBatchConvertWindow_OriginalFileFolder {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_OriginalFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string ImageBatchConvertWindow_OutputFolder {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string ImageBatchConvertWindow_Overwrite {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string ImageBatchConvertWindow_Quality {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ImageBatchConvertWindow_Rename {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as original file format.
        /// </summary>
        public static string ImageBatchConvertWindow_SameAsOriginalFileFormat {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_SameAsOriginalFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Format.
        /// </summary>
        public static string ImageBatchConvertWindow_SelectOutputFormat {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_SelectOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip (Default).
        /// </summary>
        public static string ImageBatchConvertWindow_SkipDefault {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_SkipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Convert.
        /// </summary>
        public static string ImageBatchConvertWindow_StartConvert {
            get {
                return ResourceManager.GetString("ImageBatchConvertWindow_StartConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string ImageViewPage_Rotate {
            get {
                return ResourceManager.GetString("ImageViewPage_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string ImageViewPage_ZoomIn {
            get {
                return ResourceManager.GetString("ImageViewPage_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string ImageViewPage_ZoomOut {
            get {
                return ResourceManager.GetString("ImageViewPage_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string ImageViewWindow2_Auto {
            get {
                return ResourceManager.GetString("ImageViewWindow2_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as JPG.
        /// </summary>
        public static string ImageViewWindow2_CopyAsJPG {
            get {
                return ResourceManager.GetString("ImageViewWindow2_CopyAsJPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy File.
        /// </summary>
        public static string ImageViewWindow2_CopyFile {
            get {
                return ResourceManager.GetString("ImageViewWindow2_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image.
        /// </summary>
        public static string ImageViewWindow2_CopyImage {
            get {
                return ResourceManager.GetString("ImageViewWindow2_CopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path.
        /// </summary>
        public static string ImageViewWindow2_CopyPath {
            get {
                return ResourceManager.GetString("ImageViewWindow2_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image File.
        /// </summary>
        public static string ImageViewWindow2_DeleteImageFile {
            get {
                return ResourceManager.GetString("ImageViewWindow2_DeleteImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string ImageViewWindow2_DisplayMode {
            get {
                return ResourceManager.GetString("ImageViewWindow2_DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Image.
        /// </summary>
        public static string ImageViewWindow2_EditImage {
            get {
                return ResourceManager.GetString("ImageViewWindow2_EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Image.
        /// </summary>
        public static string ImageViewWindow2_ExportImage {
            get {
                return ResourceManager.GetString("ImageViewWindow2_ExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Delete Image File.
        /// </summary>
        public static string ImageViewWindow2_FailedToDeleteImageFile {
            get {
                return ResourceManager.GetString("ImageViewWindow2_FailedToDeleteImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Display Image.
        /// </summary>
        public static string ImageViewWindow2_FailedToDisplayImage {
            get {
                return ResourceManager.GetString("ImageViewWindow2_FailedToDisplayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Save Image.
        /// </summary>
        public static string ImageViewWindow2_FailedToSaveImage {
            get {
                return ResourceManager.GetString("ImageViewWindow2_FailedToSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        public static string ImageViewWindow2_FileDoesNotExist {
            get {
                return ResourceManager.GetString("ImageViewWindow2_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to Window.
        /// </summary>
        public static string ImageViewWindow2_FitToWindow {
            get {
                return ResourceManager.GetString("ImageViewWindow2_FitToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Information.
        /// </summary>
        public static string ImageViewWindow2_ImageInformation {
            get {
                return ResourceManager.GetString("ImageViewWindow2_ImageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient permissions or the file is in use..
        /// </summary>
        public static string ImageViewWindow2_InsufficientPermissionsOrTheFileIsInUse {
            get {
                return ResourceManager.GetString("ImageViewWindow2_InsufficientPermissionsOrTheFileIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ImageViewWindow2_Next {
            get {
                return ResourceManager.GetString("ImageViewWindow2_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Image to Display.
        /// </summary>
        public static string ImageViewWindow2_NoImageToDisplay {
            get {
                return ResourceManager.GetString("ImageViewWindow2_NoImageToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer.
        /// </summary>
        public static string ImageViewWindow2_OpenInExplorer {
            get {
                return ResourceManager.GetString("ImageViewWindow2_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open New Files.
        /// </summary>
        public static string ImageViewWindow2_OpenNewFiles {
            get {
                return ResourceManager.GetString("ImageViewWindow2_OpenNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with.
        /// </summary>
        public static string ImageViewWindow2_OpenWith {
            get {
                return ResourceManager.GetString("ImageViewWindow2_OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Default App.
        /// </summary>
        public static string ImageViewWindow2_OpenWithDefaultApp {
            get {
                return ResourceManager.GetString("ImageViewWindow2_OpenWithDefaultApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ImageViewWindow2_Previous {
            get {
                return ResourceManager.GetString("ImageViewWindow2_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDR Mapped Luminance.
        /// </summary>
        public static string ImageViewWindow2_SDRMappedLuminance {
            get {
                return ResourceManager.GetString("ImageViewWindow2_SDRMappedLuminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Gallery.
        /// </summary>
        public static string ImageViewWindow2_ShowGallery {
            get {
                return ResourceManager.GetString("ImageViewWindow2_ShowGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To convert an HDR image to SDR, please use the Edit feature..
        /// </summary>
        public static string ImageViewWindow2_ToConvertAnHDRImageToSDRPleaseUseTheEditFeature {
            get {
                return ResourceManager.GetString("ImageViewWindow2_ToConvertAnHDRImageToSDRPleaseUseTheEditFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete the File.
        /// </summary>
        public static string ImageViewWindow2_UnableToDeleteTheFile {
            get {
                return ResourceManager.GetString("ImageViewWindow2_UnableToDeleteTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string LauncherPage_ConfirmDelete {
            get {
                return ResourceManager.GetString("LauncherPage_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On each tab, click the drop down of your desired game to switch regions..
        /// </summary>
        public static string MainPage_ClickTheRightMouseButtonOnTheGameIconOnTheLeft {
            get {
                return ResourceManager.GetString("MainPage_ClickTheRightMouseButtonOnTheGameIconOnTheLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string MainPage_GameScreenshot {
            get {
                return ResourceManager.GetString("MainPage_GameScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to switch game region?.
        /// </summary>
        public static string MainPage_HowToSwitchGameRegion {
            get {
                return ResourceManager.GetString("MainPage_HowToSwitchGameRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string MainPage_Tips {
            get {
                return ResourceManager.GetString("MainPage_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Glowworm! We will now check your installed HoYoverse games..
        /// </summary>
        public static string MainView_WelcomeContent {
            get {
                return ResourceManager.GetString("MainView_WelcomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Glowworm.
        /// </summary>
        public static string MainView_WelcomeTitle {
            get {
                return ResourceManager.GetString("MainView_WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program does not have permission to access the following folder. Please restart as administrator or move the folder..
        /// </summary>
        public static string NoPermissionWindow_NoPermissionToFolderRestartOrClose {
            get {
                return ResourceManager.GetString("NoPermissionWindow_NoPermissionToFolderRestartOrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart as Administrator.
        /// </summary>
        public static string NoPermissionWindow_RestartAsAdministrator {
            get {
                return ResourceManager.GetString("NoPermissionWindow_RestartAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the log for more information..
        /// </summary>
        public static string ScreenCaptureInfoWindow_CheckTheLogForMoreInformation {
            get {
                return ResourceManager.GetString("ScreenCaptureInfoWindow_CheckTheLogForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Image.
        /// </summary>
        public static string ScreenCaptureInfoWindow_ProcessingImage {
            get {
                return ResourceManager.GetString("ScreenCaptureInfoWindow_ProcessingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Failed.
        /// </summary>
        public static string ScreenCaptureInfoWindow_ScreenshotFailed {
            get {
                return ResourceManager.GetString("ScreenCaptureInfoWindow_ScreenshotFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Saved.
        /// </summary>
        public static string ScreenCaptureInfoWindow_ScreenshotSaved {
            get {
                return ResourceManager.GetString("ScreenCaptureInfoWindow_ScreenshotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string ScreenshotFolderManageDialog_AddFolder {
            get {
                return ResourceManager.GetString("ScreenshotFolderManageDialog_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up....
        /// </summary>
        public static string ScreenshotFolderManageDialog_BackingUp {
            get {
                return ResourceManager.GetString("ScreenshotFolderManageDialog_BackingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to backup screenshots..
        /// </summary>
        public static string ScreenshotFolderManageDialog_FailedToBackupScreenshots {
            get {
                return ResourceManager.GetString("ScreenshotFolderManageDialog_FailedToBackupScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images from the following folders will be displayed in the gallery..
        /// </summary>
        public static string ScreenshotFolderManageDialog_ImagesFromTheFollowingFoldersWillBeDisplayedInTheGallery {
            get {
                return ResourceManager.GetString("ScreenshotFolderManageDialog_ImagesFromTheFollowingFoldersWillBeDisplayedInTheGal" +
                        "lery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backed up {0} new screenshots..
        /// </summary>
        public static string ScreenshotPage_BackedUpNewScreenshots {
            get {
                return ResourceManager.GetString("ScreenshotPage_BackedUpNewScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Screenshots.
        /// </summary>
        public static string ScreenshotPage_BackupScreenshots {
            get {
                return ResourceManager.GetString("ScreenshotPage_BackupScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Convert.
        /// </summary>
        public static string ScreenshotPage_BatchConvert {
            get {
                return ResourceManager.GetString("ScreenshotPage_BatchConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string ScreenshotPage_GameScreenshot {
            get {
                return ResourceManager.GetString("ScreenshotPage_GameScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Screenshot Folders.
        /// </summary>
        public static string ScreenshotPage_ManageScreenshotFolders {
            get {
                return ResourceManager.GetString("ScreenshotPage_ManageScreenshotFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Select.
        /// </summary>
        public static string ScreenshotPage_MultiSelect {
            get {
                return ResourceManager.GetString("ScreenshotPage_MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot folder does not exist.
        /// </summary>
        public static string ScreenshotPage_ScreenshotFolderDoesNotExist {
            get {
                return ResourceManager.GetString("ScreenshotPage_ScreenshotFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Convert to SDR Image.
        /// </summary>
        public static string ScreenshotSetting_AutoConvertToSDRImage {
            get {
                return ResourceManager.GetString("ScreenshotSetting_AutoConvertToSDRImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Copy Screenshot File.
        /// </summary>
        public static string ScreenshotSetting_AutoCopyScreenshotFile {
            get {
                return ResourceManager.GetString("ScreenshotSetting_AutoCopyScreenshotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miliastra Wonderland Profile Pictures will be back up to the following folder.
        /// </summary>
        public static string ScreenshotSetting_BeyondProfileLocationDesc {
            get {
                return ResourceManager.GetString("ScreenshotSetting_BeyondProfileLocationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Thumbnail Cache.
        /// </summary>
        public static string ScreenshotSetting_ClearThumbnailCache {
            get {
                return ResourceManager.GetString("ScreenshotSetting_ClearThumbnailCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format and Quality.
        /// </summary>
        public static string ScreenshotSetting_FormatAndQuality {
            get {
                return ResourceManager.GetString("ScreenshotSetting_FormatAndQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-quality AVIF and JPEG XL image formats save approximately 85% of storage space..
        /// </summary>
        public static string ScreenshotSetting_HighQualityAVIFAndJPEGXLImageFormatsSaveApproximately85OfStorageSpace {
            get {
                return ResourceManager.GetString("ScreenshotSetting_HighQualityAVIFAndJPEGXLImageFormatsSaveApproximately85OfStorag" +
                        "eSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossless.
        /// </summary>
        public static string ScreenshotSetting_Lossless {
            get {
                return ResourceManager.GetString("ScreenshotSetting_Lossless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Options.
        /// </summary>
        public static string ScreenshotSetting_OtherOptions {
            get {
                return ResourceManager.GetString("ScreenshotSetting_OtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screenshot feature captures the currently running game. If multiple games are running, the most recently focused game will be selected. Note the following limitations:
        ///• Minimized game windows cannot be captured.
        ///• Parts of the game window that extend beyond the screen will not be included.
        ///• In rare cases, a non-game window may be captured instead..
        /// </summary>
        public static string ScreenshotSetting_ScreenshotFetureDescAndLimit {
            get {
                return ResourceManager.GetString("ScreenshotSetting_ScreenshotFetureDescAndLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Shortcut.
        /// </summary>
        public static string ScreenshotSetting_ScreenshotShortcut {
            get {
                return ResourceManager.GetString("ScreenshotSetting_ScreenshotShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Windows 10, the screenshot feature has the following additional limitations:
        ///• A colored border may appear around the game window during capture.
        ///• The mouse pointer cannot be hidden..
        /// </summary>
        public static string ScreenshotSetting_ScreenshotWin10Limit {
            get {
                return ResourceManager.GetString("ScreenshotSetting_ScreenshotWin10Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Screenshot.
        /// </summary>
        public static string ScreenshotSetting_TestScreenshot {
            get {
                return ResourceManager.GetString("ScreenshotSetting_TestScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The built-in screenshot feature will save images to the following folder..
        /// </summary>
        public static string ScreenshotSetting_TheBuiltInScreenshotFeatureWillSaveImagesToTheFollowingFolder {
            get {
                return ResourceManager.GetString("ScreenshotSetting_TheBuiltInScreenshotFeatureWillSaveImagesToTheFollowingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When capturing HDR images, SDR version will also be saved..
        /// </summary>
        public static string ScreenshotSetting_WhenCapturingHDRImagesSDRVersionWillAlsoBeSaved {
            get {
                return ResourceManager.GetString("ScreenshotSetting_WhenCapturingHDRImagesSDRVersionWillAlsoBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you able to receive updates for Glowworm?.
        /// </summary>
        public static string SelectLanguagePage_AreYouAbleToReceiveUpdatesForGlowworm {
            get {
                return ResourceManager.GetString("SelectLanguagePage_AreYouAbleToReceiveUpdatesForGlowworm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Test.
        /// </summary>
        public static string SelectLanguagePage_NetworkTest {
            get {
                return ResourceManager.GetString("SelectLanguagePage_NetworkTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingPage_About {
            get {
                return ResourceManager.GetString("SettingPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After deleting, the software will be restarted automatically. Proceed?.
        /// </summary>
        public static string SettingPage_AfterDeletingTheSoftwareWillBeRestartedAutomatically {
            get {
                return ResourceManager.GetString("SettingPage_AfterDeletingTheSoftwareWillBeRestartedAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string SettingPage_AppSettings {
            get {
                return ResourceManager.GetString("SettingPage_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        public static string SettingPage_BackupDatabase {
            get {
                return ResourceManager.GetString("SettingPage_BackupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users in some areas may encounter network anomalies. You could solve this problem by switching CDNs..
        /// </summary>
        public static string SettingPage_CDNTips {
            get {
                return ResourceManager.GetString("SettingPage_CDNTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Update.
        /// </summary>
        public static string SettingPage_CheckForUpdate {
            get {
                return ResourceManager.GetString("SettingPage_CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version:.
        /// </summary>
        public static string SettingPage_CurrentVersion {
            get {
                return ResourceManager.GetString("SettingPage_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Settings.
        /// </summary>
        public static string SettingPage_DeleteAllSettings {
            get {
                return ResourceManager.GetString("SettingPage_DeleteAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string SettingPage_Donate {
            get {
                return ResourceManager.GetString("SettingPage_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Management.
        /// </summary>
        public static string SettingPage_FileManagement {
            get {
                return ResourceManager.GetString("SettingPage_FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow System.
        /// </summary>
        public static string SettingPage_FollowSystem {
            get {
                return ResourceManager.GetString("SettingPage_FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a better experience, please enable the following features in system settings..
        /// </summary>
        public static string SettingPage_ForABetterExperiencePleaseEnableTheFollowingFeaturesInSystemSettings {
            get {
                return ResourceManager.GetString("SettingPage_ForABetterExperiencePleaseEnableTheFollowingFeaturesInSystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingPage_General {
            get {
                return ResourceManager.GetString("SettingPage_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Management.
        /// </summary>
        public static string SettingPage_ImageManagement {
            get {
                return ResourceManager.GetString("SettingPage_ImageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Preview Release Channel.
        /// </summary>
        public static string SettingPage_JoinPreviewReleaseChannel {
            get {
                return ResourceManager.GetString("SettingPage_JoinPreviewReleaseChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingPage_Language {
            get {
                return ResourceManager.GetString("SettingPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup.
        /// </summary>
        public static string SettingPage_LastBackup {
            get {
                return ResourceManager.GetString("SettingPage_LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string SettingPage_Log {
            get {
                return ResourceManager.GetString("SettingPage_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        public static string SettingPage_OpenLogFolder {
            get {
                return ResourceManager.GetString("SettingPage_OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Project.
        /// </summary>
        public static string SettingPage_OriginalProject {
            get {
                return ResourceManager.GetString("SettingPage_OriginalProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string SettingPage_PrivacyPolicy {
            get {
                return ResourceManager.GetString("SettingPage_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string SettingPage_ProjectHomepage {
            get {
                return ResourceManager.GetString("SettingPage_ProjectHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register URL Protocol.
        /// </summary>
        public static string SettingPage_RegisterURLProtocol {
            get {
                return ResourceManager.GetString("SettingPage_RegisterURLProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release History.
        /// </summary>
        public static string SettingPage_ReleaseHistory {
            get {
                return ResourceManager.GetString("SettingPage_ReleaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string SettingPage_ReportIssue {
            get {
                return ResourceManager.GetString("SettingPage_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan Game Directories.
        /// </summary>
        public static string SettingPage_RescanGameDirectories {
            get {
                return ResourceManager.GetString("SettingPage_RescanGameDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reselect Data Folder.
        /// </summary>
        public static string SettingPage_ReselectDataFolder {
            get {
                return ResourceManager.GetString("SettingPage_ReselectDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in System Tray.
        /// </summary>
        public static string SettingPage_RunInSystemTray {
            get {
                return ResourceManager.GetString("SettingPage_RunInSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Console.
        /// </summary>
        public static string SettingPage_ShowConsole {
            get {
                return ResourceManager.GetString("SettingPage_ShowConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current location of the data folder is:.
        /// </summary>
        public static string SettingPage_TheCurrentLocationOfTheDataFolderIs {
            get {
                return ResourceManager.GetString("SettingPage_TheCurrentLocationOfTheDataFolderIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string SettingPage_Update {
            get {
                return ResourceManager.GetString("SettingPage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Source.
        /// </summary>
        public static string SettingPage_UpdateSource {
            get {
                return ResourceManager.GetString("SettingPage_UpdateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would like to reselect? (You need to migrate the data files manually before selecting).
        /// </summary>
        public static string SettingPage_WouldLikeToReselectDataFolder {
            get {
                return ResourceManager.GetString("SettingPage_WouldLikeToReselectDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import {0} warp record(s) successfully..
        /// </summary>
        public static string StarRailGachaService_ImportWarpRecordsSuccessfully {
            get {
                return ResourceManager.GetString("StarRailGachaService_ImportWarpRecordsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; field is missing in a gacha record..
        /// </summary>
        public static string UIGFGachaService_0FieldIsMissingInAGachaRecord {
            get {
                return ResourceManager.GetString("UIGFGachaService_0FieldIsMissingInAGachaRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import successful..
        /// </summary>
        public static string UIGFGachaService_ImportSuccessful {
            get {
                return ResourceManager.GetString("UIGFGachaService_ImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import successful, but some records are missing item names. Please go to the gacha record settings, change the language, and apply..
        /// </summary>
        public static string UIGFGachaService_ImportSuccessfulButNoRecordItemName {
            get {
                return ResourceManager.GetString("UIGFGachaService_ImportSuccessfulButNoRecordItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID mismatch detected. Expected: {0}, but found: {1}..
        /// </summary>
        public static string UIGFGachaService_UidMismatchDetectedExpected0ButFound1 {
            get {
                return ResourceManager.GetString("UIGFGachaService_UidMismatchDetectedExpected0ButFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Updated Content.
        /// </summary>
        public static string UpdateContentWindow_RecentlyUpdatedContent {
            get {
                return ResourceManager.GetString("UpdateContentWindow_RecentlyUpdatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Channel.
        /// </summary>
        public static string UpdatePage_DevChannel {
            get {
                return ResourceManager.GetString("UpdatePage_DevChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Installer.
        /// </summary>
        public static string UpdatePage_DownloadInstaller {
            get {
                return ResourceManager.GetString("UpdatePage_DownloadInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Portable.
        /// </summary>
        public static string UpdatePage_DownloadPortable {
            get {
                return ResourceManager.GetString("UpdatePage_DownloadPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore this Version.
        /// </summary>
        public static string UpdatePage_IgnoreThisVersion {
            get {
                return ResourceManager.GetString("UpdatePage_IgnoreThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links:.
        /// </summary>
        public static string UpdatePage_Links {
            get {
                return ResourceManager.GetString("UpdatePage_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version!.
        /// </summary>
        public static string UpdatePage_NewVersion {
            get {
                return ResourceManager.GetString("UpdatePage_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Channel.
        /// </summary>
        public static string UpdatePage_PreviewChannel {
            get {
                return ResourceManager.GetString("UpdatePage_PreviewChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Channel:.
        /// </summary>
        public static string UpdatePage_ReleaseChannel {
            get {
                return ResourceManager.GetString("UpdatePage_ReleaseChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Page.
        /// </summary>
        public static string UpdatePage_ReleasePage {
            get {
                return ResourceManager.GetString("UpdatePage_ReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me Later.
        /// </summary>
        public static string UpdatePage_RemindLatter {
            get {
                return ResourceManager.GetString("UpdatePage_RemindLatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable Channel.
        /// </summary>
        public static string UpdatePage_StableChannel {
            get {
                return ResourceManager.GetString("UpdatePage_StableChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Now.
        /// </summary>
        public static string UpdatePage_UpdateNow {
            get {
                return ResourceManager.GetString("UpdatePage_UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to manually download the new version package.
        /// </summary>
        public static string UpdatePage_YouNeedToManuallyDownloadTheNewVersionPackage {
            get {
                return ResourceManager.GetString("UpdatePage_YouNeedToManuallyDownloadTheNewVersionPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update automatically.
        /// </summary>
        public static string UpdateService_CannotUpdateAutomatically {
            get {
                return ResourceManager.GetString("UpdateService_CannotUpdateAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-restart after update.
        /// </summary>
        public static string UpdateWindow_AutoRestartAfterUpdate {
            get {
                return ResourceManager.GetString("UpdateWindow_AutoRestartAfterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display update content after restart.
        /// </summary>
        public static string UpdateWindow_DisplayUpdateContentAfterRestart {
            get {
                return ResourceManager.GetString("UpdateWindow_DisplayUpdateContentAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import {0} signal search record(s) successfully..
        /// </summary>
        public static string ZZZGachaService_ImportSignalSearchRecordsSuccessfully {
            get {
                return ResourceManager.GetString("ZZZGachaService_ImportSignalSearchRecordsSuccessfully", resourceCulture);
            }
        }
    }
}
