//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glowworm.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glowworm.Core.Localization.CoreLang", typeof(CoreLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the warp record URL..
        /// </summary>
        public static string Gacha_CannotParseTheWarpRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWarpRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the wish record URL..
        /// </summary>
        public static string Gacha_CannotParseTheWishRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWishRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangboo Channel.
        /// </summary>
        public static string GachaType_BangbooChannel {
            get {
                return ResourceManager.GetString("GachaType_BangbooChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Collaboration Warp.
        /// </summary>
        public static string GachaType_CharacterCollaborationWarp {
            get {
                return ResourceManager.GetString("GachaType_CharacterCollaborationWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Event Warp.
        /// </summary>
        public static string GachaType_CharacterEventWarp {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Event Wish.
        /// </summary>
        public static string GachaType_CharacterEventWish {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Event Wish - 2.
        /// </summary>
        public static string GachaType_CharacterEventWish_2 {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronicled Wish.
        /// </summary>
        public static string GachaType_ChronicledWish {
            get {
                return ResourceManager.GetString("GachaType_ChronicledWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Warp.
        /// </summary>
        public static string GachaType_DepartureWarp {
            get {
                return ResourceManager.GetString("GachaType_DepartureWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Ode.
        /// </summary>
        public static string GachaType_EventOde {
            get {
                return ResourceManager.GetString("GachaType_EventOde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Channel.
        /// </summary>
        public static string GachaType_ExclusiveChannel {
            get {
                return ResourceManager.GetString("GachaType_ExclusiveChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Rescreening.
        /// </summary>
        public static string GachaType_ExclusiveRescreening {
            get {
                return ResourceManager.GetString("GachaType_ExclusiveRescreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Cone Collaboration Warp.
        /// </summary>
        public static string GachaType_LightConeCollaborationWarp {
            get {
                return ResourceManager.GetString("GachaType_LightConeCollaborationWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Cone Event Warp.
        /// </summary>
        public static string GachaType_LightConeEventWarp {
            get {
                return ResourceManager.GetString("GachaType_LightConeEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice Wish.
        /// </summary>
        public static string GachaType_NoviceWish {
            get {
                return ResourceManager.GetString("GachaType_NoviceWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Wish.
        /// </summary>
        public static string GachaType_PermanentWish {
            get {
                return ResourceManager.GetString("GachaType_PermanentWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Channel.
        /// </summary>
        public static string GachaType_StandardChannel {
            get {
                return ResourceManager.GetString("GachaType_StandardChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Ode.
        /// </summary>
        public static string GachaType_StandardOde {
            get {
                return ResourceManager.GetString("GachaType_StandardOde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellar Warp.
        /// </summary>
        public static string GachaType_StellarWarp {
            get {
                return ResourceManager.GetString("GachaType_StellarWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Event Wish.
        /// </summary>
        public static string GachaType_WeaponEventWish {
            get {
                return ResourceManager.GetString("GachaType_WeaponEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W-Engine Channel.
        /// </summary>
        public static string GachaType_WEngineChannel {
            get {
                return ResourceManager.GetString("GachaType_WEngineChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W-Engine Reverberation.
        /// </summary>
        public static string GachaType_WEngineReverberation {
            get {
                return ResourceManager.GetString("GachaType_WEngineReverberation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genshin Impact.
        /// </summary>
        public static string Game_GenshinImpact {
            get {
                return ResourceManager.GetString("Game_GenshinImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honkai: Star Rail.
        /// </summary>
        public static string Game_HonkaiStarRail {
            get {
                return ResourceManager.GetString("Game_HonkaiStarRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zenless Zone Zero.
        /// </summary>
        public static string Game_ZZZ {
            get {
                return ResourceManager.GetString("Game_ZZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiliBili.
        /// </summary>
        public static string GameServer_Bilibili {
            get {
                return ResourceManager.GetString("GameServer_Bilibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Cloud Server.
        /// </summary>
        public static string GameServer_ChinaCloud {
            get {
                return ResourceManager.GetString("GameServer_ChinaCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Server.
        /// </summary>
        public static string GameServer_ChinaServer {
            get {
                return ResourceManager.GetString("GameServer_ChinaServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Cloud Server.
        /// </summary>
        public static string GameServer_GlobalCloud {
            get {
                return ResourceManager.GetString("GameServer_GlobalCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Server.
        /// </summary>
        public static string GameServer_GlobalServer {
            get {
                return ResourceManager.GetString("GameServer_GlobalServer", resourceCulture);
            }
        }
    }
}
