//------------------------------------------------------------------------------
// <auto-generated>
//     ?????????
//     ?????:4.0.30319.42000
//
//     ??????????????????,????
//     ??????,?????????
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glowworm.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   ?????????,?????????????
    /// </summary>
    // ???? StronglyTypedResourceBuilder
    // ?????? ResGen ? Visual Studio ?????????
    // ?????????,??? .ResX ??,?????? ResGen
    // (? /str ??????),????? VS ???
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLang() {
        }
        
        /// <summary>
        ///   ?????????? ResourceManager ???
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glowworm.Core.Localization.CoreLang", typeof(CoreLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   ??????? CurrentUICulture ??,?
        ///   ?????????????????????
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ???? Cannot parse the warp record URL. ????????
        /// </summary>
        public static string Gacha_CannotParseTheWarpRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWarpRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Cannot parse the wish record URL. ????????
        /// </summary>
        public static string Gacha_CannotParseTheWishRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWishRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Bangboo Channel ????????
        /// </summary>
        public static string GachaType_BangbooChannel {
            get {
                return ResourceManager.GetString("GachaType_BangbooChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Character Collaboration Warp ????????
        /// </summary>
        public static string GachaType_CharacterCollaborationWarp {
            get {
                return ResourceManager.GetString("GachaType_CharacterCollaborationWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Character Event Warp ????????
        /// </summary>
        public static string GachaType_CharacterEventWarp {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Character Event Wish ????????
        /// </summary>
        public static string GachaType_CharacterEventWish {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Character Event Wish - 2 ????????
        /// </summary>
        public static string GachaType_CharacterEventWish_2 {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Chronicled Wish ????????
        /// </summary>
        public static string GachaType_ChronicledWish {
            get {
                return ResourceManager.GetString("GachaType_ChronicledWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Departure Warp ????????
        /// </summary>
        public static string GachaType_DepartureWarp {
            get {
                return ResourceManager.GetString("GachaType_DepartureWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Event Ode ????????
        /// </summary>
        public static string GachaType_EventOde {
            get {
                return ResourceManager.GetString("GachaType_EventOde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Exclusive Channel ????????
        /// </summary>
        public static string GachaType_ExclusiveChannel {
            get {
                return ResourceManager.GetString("GachaType_ExclusiveChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Exclusive Rescreening ????????
        /// </summary>
        public static string GachaType_ExclusiveRescreening {
            get {
                return ResourceManager.GetString("GachaType_ExclusiveRescreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Light Cone Collaboration Warp ????????
        /// </summary>
        public static string GachaType_LightConeCollaborationWarp {
            get {
                return ResourceManager.GetString("GachaType_LightConeCollaborationWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Light Cone Event Warp ????????
        /// </summary>
        public static string GachaType_LightConeEventWarp {
            get {
                return ResourceManager.GetString("GachaType_LightConeEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Novice Wish ????????
        /// </summary>
        public static string GachaType_NoviceWish {
            get {
                return ResourceManager.GetString("GachaType_NoviceWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Permanent Wish ????????
        /// </summary>
        public static string GachaType_PermanentWish {
            get {
                return ResourceManager.GetString("GachaType_PermanentWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Standard Channel ????????
        /// </summary>
        public static string GachaType_StandardChannel {
            get {
                return ResourceManager.GetString("GachaType_StandardChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Standard Ode ????????
        /// </summary>
        public static string GachaType_StandardOde {
            get {
                return ResourceManager.GetString("GachaType_StandardOde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Stellar Warp ????????
        /// </summary>
        public static string GachaType_StellarWarp {
            get {
                return ResourceManager.GetString("GachaType_StellarWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Weapon Event Wish ????????
        /// </summary>
        public static string GachaType_WeaponEventWish {
            get {
                return ResourceManager.GetString("GachaType_WeaponEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? W-Engine Channel ????????
        /// </summary>
        public static string GachaType_WEngineChannel {
            get {
                return ResourceManager.GetString("GachaType_WEngineChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? W-Engine Reverberation ????????
        /// </summary>
        public static string GachaType_WEngineReverberation {
            get {
                return ResourceManager.GetString("GachaType_WEngineReverberation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Genshin Impact ????????
        /// </summary>
        public static string Game_GenshinImpact {
            get {
                return ResourceManager.GetString("Game_GenshinImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Honkai: Star Rail ????????
        /// </summary>
        public static string Game_HonkaiStarRail {
            get {
                return ResourceManager.GetString("Game_HonkaiStarRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Zenless Zone Zero ????????
        /// </summary>
        public static string Game_ZZZ {
            get {
                return ResourceManager.GetString("Game_ZZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Bilibili ????????
        /// </summary>
        public static string GameServer_Bilibili {
            get {
                return ResourceManager.GetString("GameServer_Bilibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Bilibili Server ????????
        /// </summary>
        public static string GameServer_BilibiliServer {
            get {
                return ResourceManager.GetString("GameServer_BilibiliServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? China Cloud ????????
        /// </summary>
        public static string GameServer_ChinaCloud {
            get {
                return ResourceManager.GetString("GameServer_ChinaCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? China Cloud Server ????????
        /// </summary>
        public static string GameServer_ChinaCloudServer {
            get {
                return ResourceManager.GetString("GameServer_ChinaCloudServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? China Official ????????
        /// </summary>
        public static string GameServer_ChinaOfficial {
            get {
                return ResourceManager.GetString("GameServer_ChinaOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? China Server ????????
        /// </summary>
        public static string GameServer_ChinaServer {
            get {
                return ResourceManager.GetString("GameServer_ChinaServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Europe &amp; Americas ????????
        /// </summary>
        public static string GameServer_EuropeAmericas {
            get {
                return ResourceManager.GetString("GameServer_EuropeAmericas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Europe &amp; Americas Servers ????????
        /// </summary>
        public static string GameServer_EuropeAmericasServers {
            get {
                return ResourceManager.GetString("GameServer_EuropeAmericasServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Global Official ????????
        /// </summary>
        public static string GameServer_GlobalOfficial {
            get {
                return ResourceManager.GetString("GameServer_GlobalOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Global Server ????????
        /// </summary>
        public static string GameServer_GlobalServer {
            get {
                return ResourceManager.GetString("GameServer_GlobalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Global Cloud ????????
        /// </summary>
        public static string GameServer_GlobalCloud {
            get {
                return ResourceManager.GetString("GameServer_GlobalCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Japan ????????
        /// </summary>
        public static string GameServer_Japan {
            get {
                return ResourceManager.GetString("GameServer_Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Japan Server ????????
        /// </summary>
        public static string GameServer_JapanServer {
            get {
                return ResourceManager.GetString("GameServer_JapanServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Korea ????????
        /// </summary>
        public static string GameServer_Korea {
            get {
                return ResourceManager.GetString("GameServer_Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Korea Server ????????
        /// </summary>
        public static string GameServer_KoreaServer {
            get {
                return ResourceManager.GetString("GameServer_KoreaServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Southeast Asia Server ????????
        /// </summary>
        public static string GameServer_SEAServer {
            get {
                return ResourceManager.GetString("GameServer_SEAServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Southeast Asia ????????
        /// </summary>
        public static string GameServer_SoutheastAsia {
            get {
                return ResourceManager.GetString("GameServer_SoutheastAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Traditional Chinese ????????
        /// </summary>
        public static string GameServer_TraditionalChinese {
            get {
                return ResourceManager.GetString("GameServer_TraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Traditional Chinese Server ????????
        /// </summary>
        public static string GameServer_TraditionalChineseServer {
            get {
                return ResourceManager.GetString("GameServer_TraditionalChineseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? CBT3 ????????
        /// </summary>
        public static string GameServer_ZZZCBT3 {
            get {
                return ResourceManager.GetString("GameServer_ZZZCBT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Arcane Keystone ????????
        /// </summary>
        public static string GenshinQueryType_ArcaneKeystone {
            get {
                return ResourceManager.GetString("GenshinQueryType_ArcaneKeystone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Artifacts ????????
        /// </summary>
        public static string GenshinQueryType_Artifact {
            get {
                return ResourceManager.GetString("GenshinQueryType_Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Chronal Nexus ????????
        /// </summary>
        public static string GenshinQueryType_ChronalNexus {
            get {
                return ResourceManager.GetString("GenshinQueryType_ChronalNexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Genesis Crystals ????????
        /// </summary>
        public static string GenshinQueryType_GenesisCrystal {
            get {
                return ResourceManager.GetString("GenshinQueryType_GenesisCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Original Resins ????????
        /// </summary>
        public static string GenshinQueryType_OriginalResin {
            get {
                return ResourceManager.GetString("GenshinQueryType_OriginalResin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Primogems ????????
        /// </summary>
        public static string GenshinQueryType_Primogem {
            get {
                return ResourceManager.GetString("GenshinQueryType_Primogem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Weapons ????????
        /// </summary>
        public static string GenshinQueryType_Weapon {
            get {
                return ResourceManager.GetString("GenshinQueryType_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Events ????????
        /// </summary>
        public static string PostType_Activity {
            get {
                return ResourceManager.GetString("PostType_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Notices ????????
        /// </summary>
        public static string PostType_Announcement {
            get {
                return ResourceManager.GetString("PostType_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Info ????????
        /// </summary>
        public static string PostType_Information {
            get {
                return ResourceManager.GetString("PostType_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Light Cone ????????
        /// </summary>
        public static string StarRailQueryType_LightCone {
            get {
                return ResourceManager.GetString("StarRailQueryType_LightCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Oneiric Shared ????????
        /// </summary>
        public static string StarRailQueryType_OneiricShared {
            get {
                return ResourceManager.GetString("StarRailQueryType_OneiricShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Relic ????????
        /// </summary>
        public static string StarRailQueryType_Relic {
            get {
                return ResourceManager.GetString("StarRailQueryType_Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Stellar Jade ????????
        /// </summary>
        public static string StarRailQueryType_StellarJade {
            get {
                return ResourceManager.GetString("StarRailQueryType_StellarJade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Trailblaze Power ????????
        /// </summary>
        public static string StarRailQueryType_TrailblazePower {
            get {
                return ResourceManager.GetString("StarRailQueryType_TrailblazePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Battery Charge ????????
        /// </summary>
        public static string ZZZQueryType_BatteryCharge {
            get {
                return ResourceManager.GetString("ZZZQueryType_BatteryCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Bundle ????????
        /// </summary>
        public static string ZZZQueryType_Bundle {
            get {
                return ResourceManager.GetString("ZZZQueryType_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Drive Disc ????????
        /// </summary>
        public static string ZZZQueryType_DriveDisc {
            get {
                return ResourceManager.GetString("ZZZQueryType_DriveDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Monochrome ????????
        /// </summary>
        public static string ZZZQueryType_Monochrome {
            get {
                return ResourceManager.GetString("ZZZQueryType_Monochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? Ploychrome ????????
        /// </summary>
        public static string ZZZQueryType_Ploychrome {
            get {
                return ResourceManager.GetString("ZZZQueryType_Ploychrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ???? W-Engine ????????
        /// </summary>
        public static string ZZZQueryType_WEngine {
            get {
                return ResourceManager.GetString("ZZZQueryType_WEngine", resourceCulture);
            }
        }
    }
}



